netobserv/network-observability-operator

- config/rbac/role.yaml
- config/samples/flows_v1alpha1_flowcollector.yaml
- controllers/flowcollector_controller.go
- controllers/goflowkube/goflowkube_objects.go
- controllers/goflowkube/goflowkube_reconciler.go
- controllers/goflowkube/goflowkube_test.go
Implement installing a configmap for goflow-kube
> Fix goflow-kube deployment - works with configmap

- api/v1alpha1/flowcollector_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/flows.netobserv.io_flowcollectors.yaml
- controllers/flowcollector_controller.go
- controllers/goflowkube/goflowkube_objects.go
- controllers/goflowkube/goflowkube_reconciler.go
- controllers/goflowkube/goflowkube_test.go
Binded FlowCollectorGoflowKube port + FlowCollectorLoki fields to ConfigMap
Set static Labels
Usage of structs & json.Marshal makes the code easy to read / update
> [NETOBSERV-34] [NETOBSERV-87] ConfigMap fields

- README.md
- config/manager/manager.yaml
- config/samples/net-cluster-patch.json
- Using existing images built by CI
- note on pull policy
- applying CR
- configuriing OVS
> Improve documentation

- Dockerfile
- Makefile
- OWNERS
- go.mod
- vendor/modules.txt
> Add vendors in Dockerfile and avoid mod download

- controllers/flowcollector_controller_test.go
- controllers/ovs/flowsconfig.go
Fixes two issues:
* When deploying Goflow as a Daemonset, it returns an "unexpected kind DaemonSet" error.
* During the undeployment, if the ovs-flows-config map did not exist, it keeped retrying without finalizing the undeployment.
Jira issue: https://issues.redhat.com/browse/NETOBSERV-66
> [NETOBSERV-66] Bug fixes: deploying as a DaemonSet and removing configmap

- README.md
- controllers/consoleplugin/consoleplugin_objects.go
dependent on this PR: https://github.com/netobserv/network-observability-console-plugin/pull/8
also added a patch command to the readme for easier setup
> Update console plugin arguments

- Makefile
- README.md
(also fix catalog-build for podman)
> Add quay.io build badge

- Makefile
- README.md
the documentation wasn't up to date wrt OVS config & openshift 4.10.
Also, I added a make target to more simply create a sample FlowCollector resource
> Update documentation for OVS config; add make create-sample

- config/samples/dashboards/Network Observability.json
Add flows by namespaces + total flows metrics
> Update Grafana dashboard

- config/samples/flows_v1alpha1_flowcollector.yaml
Add the `healthPort` property to the sample deployment.
> Fix sample deployment

- api/v1alpha1/flowcollector_types.go
- bundle/manifests/flows.netobserv.io_flowcollectors.yaml
- config/crd/bases/flows.netobserv.io_flowcollectors.yaml
- controllers/flowcollector_controller_test.go
- controllers/goflowkube/goflowkube_reconciler.go
- docs/FlowCollector.md
My understanding is that we cannot check everything here with kubebuilder annotations.
So, I added a verification function.
> NETOBSERV-148 Added goflowkube port verifications

- api/v1alpha1/flowcollector_types.go
- config/crd/bases/flows.netobserv.io_flowcollectors.yaml
- config/manager/manager.yaml
- docs/FlowCollector.md
Added default values for resources requests, we may need to adapt them once we perform more performance tests.
> NETOBSERV-89 : Added default resources values

- Makefile
E.g. PORT_FWD=false make deploy-loki deploy-grafana
> Make port-forward optional in deploy-loki / grafana

- Makefile
- README.md
- bundle/manifests/netobserv-operator.clusterserviceversion.yaml
- config/manifests/bases/netobserv-operator.clusterserviceversion.yaml
- config/samples/dashboards/Network Observability.json
- config/samples/flows_v1alpha1_flowcollector.yaml
- config/samples/flows_v1alpha1_flowcollector_versioned.yaml
- [NETOBSERV-261](https://issues.redhat.com/browse/NETOBSERV-261) Update grafana dashboard and manage versioning
- [NETOBSERV-242](https://issues.redhat.com/browse/NETOBSERV-242) Update operator description
> NETOBSERV-242 - NETOBSERV-261 operator description + update grafana dashboard

- Makefile
- RELEASE.md
- api/v1alpha1/flowcollector_types.go
- config/crd/bases/flows.netobserv.io_flowcollectors.yaml
- docs/FlowCollector.md
@mariomac : adding to the agent field description: "The eBPF agent is not officially released yet, it is provided as a preview."
> Update release info, include eBPF

- config/samples/dashboards/Network Observability.json
Removed extra information that was preventing dashboards from showing up.
> NETOBSERV-297 (v0.1.1) Some Grafana dashboards are not showing up

- .github/workflows/release.yml
- RELEASE.md
(I only partially tested, need to run an actual release to fully validate)
> Automate catalog push and remove it from manual release steps

- RELEASE.md
- bundle/manifests/netobserv-operator.clusterserviceversion.yaml
Just adding some info when publishing a new release
> Update release doc

- .mk/ocp.mk
- hack/refresh-ovs.sh
ie. reset its configuration so that it sends again the ipfix templates
goal is to speed up ipfix template sync
> Hack script to "refresh" OVS

- controllers/consoleplugin/consoleplugin_objects.go
- controllers/consoleplugin/consoleplugin_test.go
Also remove duplicated code for plugin args
> NETOBSERV-504 Fix console plugin bool flags usage

- Makefile
- RELEASE.md
- bundle.Dockerfile
- bundle/metadata/annotations.yaml
- controllers/flowcollector_controller_console_test.go
- Auto-update previous version as part of make bundle
- Document testing the upgrade path
> Improve release doc & script

- .mk/development.mk
Updating kafka make targets for https://github.com/netobserv/documents/pull/30/files
> Kafka mk targets

- controllers/flowlogspipeline/flp_common_objects.go
My changes after code review introduced a bug, FLP host token needs to be configured in both modes.
> Fix auth token mode for FLP

- DEVELOPMENT.md
- config/manager/manager.yaml
`oc set env` or `kubectl set env` is a much more convenient tool for changing the related images.
> Amend image patching instructions

- api/v1alpha1/flowcollector_types.go
- bundle/manifests/flows.netobserv.io_flowcollectors.yaml
- config/crd/bases/flows.netobserv.io_flowcollectors.yaml
- docs/FlowCollector.md
- docs/GeneratingAsciidocAPI.md
- docs/flowcollector-flows-netobserv-io-v1alpha1.adoc
> Update Kafka exporter doc, add instruction to generate ascidoc

- DEVELOPMENT.md
- hack/enable-metrics.sh
Temporary shell script to enable viewing of flp metrics in the console.
> Enable metrics in console

- README.md
- bundle/manifests/netobserv-operator.clusterserviceversion.yaml
- config/manifests/bases/description-ocp.md
- config/manifests/bases/description-upstream.md
Couple of minor changes here for polish - let me know your thoughts!
> Updates to manifests descriptions

- .github/workflows/pull_request.yml
- .github/workflows/push_image.yml
- .github/workflows/push_image_pr.yml
- .github/workflows/release.yml
- .github/workflows/rm-ok-to-test.yaml
- Dockerfile
> NETOBSERV-757 github actions maintenance + add CI test to replace prow

- controllers/consoleplugin/consoleplugin_reconciler.go
- controllers/consoleplugin/consoleplugin_test.go
- controllers/flowlogspipeline/flp_ingest_reconciler.go
- controllers/flowlogspipeline/flp_monolith_reconciler.go
- controllers/flowlogspipeline/flp_test.go
- controllers/flowlogspipeline/flp_transfo_reconciler.go
- pkg/helper/change_report.go
- pkg/helper/comparators.go
Backport of https://github.com/netobserv/network-observability-operator/pull/262
> NETOBSERV-856 [1.2 backport] Fix infinite reconcile & add more debugging utility

- controllers/consoleplugin/consoleplugin_objects.go
backport of https://github.com/netobserv/network-observability-operator/pull/320/commits/61cb3da84a2ef5a00089a48fe22478dcd438680e
> [Backport] NETOBSERV-844 skip empty cert paths

- .github/workflows/push_image_pr.yml
Reverts netobserv/network-observability-operator#348
> Revert "Dummy PR test bundle/catalog GH push flow"

- DEVELOPMENT.md
(just some more internal doc about how to test upgrades)
> Update dev doc

- Makefile
- pkg/dashboards/infra_health_dashboard.json
> NETOBSERV-1434: update health dashboard for changed operator metric

- .github/workflows/pull_request.yml
- .github/workflows/push_image.yml
- .github/workflows/push_image_pr.yml
- .github/workflows/release.yml
- .golangci.yml
- Dockerfile
> NETOBSERV-1451: Bump ubi 9.3 / go 1.21

- controllers/consoleplugin/config/static-frontend-config.yaml
Backport of https://github.com/netobserv/network-observability-operator/pull/544
> Fix flow layer name [1.5 backport]

- controllers/consoleplugin/config/config.go
- controllers/consoleplugin/config/static-frontend-config.yaml
- controllers/consoleplugin/consoleplugin_objects.go
- controllers/constants/constants.go
- pkg/loki/labels.go
Backport of https://github.com/netobserv/network-observability-operator/pull/546
> NETOBSERV-1214 & NETOBSERV-1399 Backport

- bundle/manifests/netobserv-operator.clusterserviceversion.yaml
- config/descriptions/ocp.md
- config/descriptions/upstream.md
link to doc downstream was broken
Also update a few link, particularly the permalink to zero-click loki
n/a
> NETOBSERV-1544: fix broken link and update a few other links in CSV

- apis/flowcollector/v1beta2/flowcollector_types.go
- bundle/manifests/flows.netobserv.io_flowcollectors.yaml
- config/crd/bases/flows.netobserv.io_flowcollectors.yaml
- docs/FlowCollector.md
> OCPBUGS-30191: typo omited->omitted

- apis/flowcollector/v1beta1/flowcollector_types.go
- apis/flowcollector/v1beta2/flowcollector_types.go
- bundle/manifests/flows.netobserv.io_flowcollectors.yaml
- config/crd/bases/flows.netobserv.io_flowcollectors.yaml
- controllers/consoleplugin/config/static-frontend-config.yaml
- docs/FlowCollector.md
> Replace "handshake RTT" mentions with "smoothed RTT"

- .github/workflows/pull_request.yml
- .github/workflows/push_image.yml
- .github/workflows/push_image_pr.yml
- .github/workflows/release.yml
- .golangci.yml
- Dockerfile
> NETOBSERV-1707: move to go 1.22

- controllers/ebpf/agent_controller.go
update filter agent configs
https://github.com/netobserv/netobserv-ebpf-agent/pull/359
> NETOBSERV-1617: generalize flow filter so it can be used with  pcap feature

- .tekton/network-observability-operator-pull-request.yaml
- .tekton/network-observability-operator-push.yaml
Restrict konflux to test branch
> Restrict konflux to test branch

- .tekton/network-observability-operator-pull-request.yaml
- .tekton/network-observability-operator-push.yaml
> Remove base images ref in konflux config

- controllers/ebpf/agent_controller.go
Backport of https://github.com/netobserv/network-observability-operator/pull/738
> [Backport] NETOBSERV-1779 allow port filtering if protocol not set

- controllers/consoleplugin/config/static-frontend-config.yaml
Restore icmp fields configurations
n/a
> NETOBSERV-1806 ICMP type are showing as n/a for icmp traffic

- controllers/ebpf/agent_controller.go
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
(cherry picked from commit 6faff0a419c930bf0d32ac3eaef25f9f5ca9ba80)
n/a
> fix filter icmp pointer check [BP 1.6,.2]

- controllers/ebpf/agent_controller.go
> fix filter icmp pointer check

- hack/patch_catalog.py
- hack/update-build.sh
Update catalog file to point to downstream bundle
> Update catalog file to point to downstream bundle

- .tekton/network-observability-operator-bundle-pull-request.yaml
- .tekton/network-observability-operator-bundle-push.yaml
- .tekton/network-observability-operator-fbc-pull-request.yaml
- .tekton/network-observability-operator-fbc-push.yaml
- .tekton/network-observability-operator-pull-request.yaml
- .tekton/network-observability-operator-push.yaml
Add missing dependencies to build scripts
> Add missing dependencies to build scripts

- hack/patch_catalog.py
- hack/patch_csv.py
> Fix image reference

- .tekton/network-observability-operator-bundle-pull-request.yaml
- .tekton/network-observability-operator-bundle-push.yaml
- .tekton/network-observability-operator-fbc-pull-request.yaml
- .tekton/network-observability-operator-fbc-push.yaml
- .tekton/network-observability-operator-pull-request.yaml
- .tekton/network-observability-operator-push.yaml
- hack/update-build.sh
- adding missing hermetic flag
- adding description label
- using downstream image for update-build.sh task (not sure about this fix but release pipeline only run on main)
n/a
> NETOBSERV-1633: Fix operator konflux build violations

- controllers/monitoring/monitoring_controller.go
Promote 'netobserv-managed' label on namespace too.
n/a
> NETOBSERV-1811 promote managed label

- apis/flowcollector/v1beta2/flowcollector_types.go
- bundle/manifests/flows.netobserv.io_flowcollectors.yaml
- config/crd/bases/flows.netobserv.io_flowcollectors.yaml
- docs/FlowCollector.md
Backport of https://github.com/netobserv/network-observability-operator/pull/811
> Networkevents feature is DevPreview [1.7 backport]

- apis/flowcollector/v1beta2/flowcollector_types.go
- bundle/manifests/flows.netobserv.io_flowcollectors.yaml
- config/crd/bases/flows.netobserv.io_flowcollectors.yaml
- docs/FlowCollector.md
- docs/flowcollector-flows-netobserv-io-v1beta2.adoc
cf https://github.com/netobserv/network-observability-operator/pull/796 comments .. merged too fast
> API docs: fix missed feedback

- .github/workflows/push_image.yml
- .github/workflows/push_image_pr.yml
- .github/workflows/release.yml
- Dockerfile
- Makefile
Reducing the Dockerfile dependencies allows faster dev builds
> Align build steps - distinguish clean vs dev builds

- hack/container_digest.sh
> Update image reference to point to final repository

- .tekton/network-observability-operator-1-7-push.yaml
- .tekton/network-observability-operator-bundle-1-7-push.yaml
- .tekton/pipeline-ref.yaml
Added missing rpms check task in konflux
n/a
> Added missing rpms check task in konflux

- .tekton/pipeline-bundle-ref.yaml
> Fixing bundle build

- bundle.Dockerfile.downstream
- hack/patch_csv.py
Add imageref in csv during bundle build
n/a
> Add imageref in csv during bundle build

- hack/bundle_digest.sh
Bumping bundle digest in fbc configuration file
n/a
> Bumping bundle digest in fbc configuration file

- hack/patch_csv.py
> Change rbac-proxy URL

- .tekton/pipeline-ref.yaml
Konflux: fixing image source tagging
n/a
> Konflux: fixing image source tagging

- .tekton/pipeline-ref.yaml
> Fix konflux results

- hack/bundle_digest.sh
> Bumping bundle

- hack/bundle_digest.sh
Bumping bundle digest in fbc
n/a
> Bumping bundle digest in fbc

- .tekton/network-observability-operator-fbc-1-7-push.yaml
> Add latest tag to fbc

- .tekton/network-observability-operator-fbc-1-7-412-pull-request.yaml
- .tekton/network-observability-operator-fbc-1-7-412-push.yaml
- .tekton/pipeline-fbc-ref.yaml
Use 4.12 opm in 4.12 fbc pipeline
n/a
> Use 4.12 opm in 4.12 fbc pipeline

- hack/bundle_digest.sh
Bumping bundle digest in catalog
n/a
> Bumping bundle digest in catalog

- hack/container_digest.sh
Update container digest in bundle
n/a
> Update container digest in bundle

- apis/flowcollector/v1beta1/flowcollector_types.go
- apis/flowcollector/v1beta2/flowcollector_types.go
- bundle/manifests/flows.netobserv.io_flowcollectors.yaml
- config/crd/bases/flows.netobserv.io_flowcollectors.yaml
- config/samples/flows_v1beta2_flowcollector.yaml
- controllers/consoleplugin/config/static-frontend-config.yaml
- controllers/consoleplugin/consoleplugin_objects.go
- controllers/ebpf/agent_controller.go
- controllers/flp/flp_pipeline_builder.go
- docs/FlowCollector.md
- pkg/helper/flowcollector.go
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
n/a
> NETOBSERV-1965: packet translation feature support

- pkg/dashboards/health.go
Small PR to add a chart in the health dashboards that shows actual metrics cardinality
cc @memodi
> Health: show metrics cardinality

- docs/Konflux.md
Creating konflux documentation
n/a
> Creating konflux documentation

- hack/container_digest.sh
> Adding lines in digest file to reduce conflicts

- controllers/consoleplugin/config/static-frontend-config.yaml
rename xlat icmp field
https://github.com/netobserv/netobserv-ebpf-agent/pull/508
> NETOBSERV-2055: remove xlatIcmpId 

- .tekton/pipeline-bundle-ref.yaml
- .tekton/pipeline-ref.yaml
> Removing konflux deprecated results

- apis/flowcollector/v1beta2/flowcollector_types.go
- apis/flowcollector/v1beta2/flowcollector_validation_webhook.go
- apis/flowcollector/v1beta2/flowcollector_validation_webhook_test.go
- bundle/manifests/flows.netobserv.io_flowcollectors.yaml
- config/crd/bases/flows.netobserv.io_flowcollectors.yaml
- config/samples/flows_v1beta2_flowcollector.yaml
- docs/FlowCollector.md
- Warn on performance impacts when using conntrack All
- Make conntrack+no-loki invalid
n/a
> NETOBSERV-1956: NETOBSERV-1957: webhook conntrack cases

- hack/bundle_digest.sh
> Fixing bundle digest

- hack/container_digest.sh
> Fixe typo in bundle images digests (#1075)

- hack/container_digest.sh
> 1.8 digest update

- .tekton/network-observability-operator-fbc-1-8-push.yaml
> Changing fbc tag to 1.8

- hack/container_digest.sh
> release-1.8 Bumping images digests

- hack/bundle_digest.sh
> Bumping bundle digest

- hack/container_digest.sh
> release-1.8 Konflux bump bundle

- hack/bundle_digest.sh
Bumping bundle image in catalog
n/a
> Bumping bundle image in catalog

- hack/container_digest.sh
> release-1.8: Bumping images in bundle

- .github/workflows/pr-labels.yaml
This should help for release notes categorization
> Label konflux PRs as dependency

- hack/container_digest.sh
> Bumping images in bundle

- hack/bundle_digest.sh
> Bumping bundle in FBC

- Dockerfile.downstream
cf https://github.com/netobserv/network-observability-operator/pull/1135
> FIPS compliance

- hack/container_digest.sh
> release-1.8 Bumping images in bundle

- hack/bundle_digest.sh
> release-1.8 Bumping bundle in fbc

- .tekton/fbc-v4-18-pull-request.yaml
- .tekton/fbc-v4-18-push.yaml
> Fixing konflux configuration for fbc 4.18

- hack/bundle_digest.sh
- hack/container_digest.sh
Using release snapshot: netobserv-operator-1-8-9ms9w
> Prepare 1.8 fbc

- .tekton/pipeline-fbc-ref.yaml
> Konflux: pinning validate-fbc task in konflux

- .tekton/pipeline-fbc-ref.yaml
> Konflux: Removing sbom task which as been deprecated

- .tekton/pipeline-fbc-ref.yaml
- hack/patch_csv.py
This task blocks the release, see https://github.com/konflux-ci/konflux-test/pull/368
> Temporary skipping fbc-fips-check-oci-ta

- .mk/development.mk
- Makefile
- README.md
- config/kind/deployment-prometheus.yaml
- helm/Chart.yaml
- helm/LICENSE
- helm/README.md
- Add more metadata
- Improve readme
- Fix a couple of issues deploying prometheus
- add license
> Improve helm chart

- Dockerfile.downstream
> NETOBSERV-2150: add license to downstream container

- hack/nudging/container_digest.sh
Image created from 'https://github.com/netobserv/network-observability-console-plugin?rev=e4709b1c5e0fcd21f59319afa2a3e733500fe458'
n/a
> chore(deps): update network-observability-console-plugin-1-8 to 4e3953b

- renovate.json
I'd like to do a try with renovate auto-merge
> Renovate auto-merge

- apis/flowcollector/v1beta1/flowcollector_types.go
- apis/flowcollector/v1beta2/flowcollector_types.go
- bundle/manifests/flows.netobserv.io_flowcollectors.yaml
- config/crd/bases/flows.netobserv.io_flowcollectors.yaml
- controllers/ebpf/internal/permissions/permissions.go
- docs/FlowCollector.md
- helm/templates/flows.netobserv.io_flowcollectors.yaml
> CRD doc: update feature statuses

- .ci-operator.yaml
> Fix .ci-operator base image

- releases/1.9.2/fbc-4-12.yaml
- releases/1.9.2/fbc-4-14.yaml
- releases/1.9.2/fbc-4-15.yaml
- releases/1.9.2/fbc-4-16.yaml
- releases/1.9.2/fbc-4-17.yaml
- releases/1.9.2/fbc-4-18.yaml
- releases/1.9.2/fbc-4-19.yaml
- releases/1.9.2/fbc-4-20.yaml
- releases/1.9.2/netobserv.yaml
> Add yaml object used to release 1.9.2

- hack/helm-update.sh
- helm/templates/certificate.yaml
- helm/templates/deployment.yaml
- helm/values.yaml
> added support of Node Affinity and custom cluster domain

- bundle.Dockerfile
- bundle.Dockerfile.downstream
> Bundle bump 5

- FAQ.md
- api/flowcollector/v1beta2/flowcollector_types.go
- bundle/manifests/flows.netobserv.io_flowcollectors.yaml
- bundle/manifests/netobserv-operator.clusterserviceversion.yaml
- config/crd/bases/flows.netobserv.io_flowcollectors.yaml
- config/descriptions/ocp.md
- config/descriptions/upstream.md
- docs/FlowCollector.md
- helm/crds/flows.netobserv.io_flowcollectors.yaml
- internal/controller/consoleplugin/config/static-frontend-config.yaml
Just doc/text renamings...
n/a
> NETOBSERV-2355: Rename sampling ratio/rate -> interval
