config/crd/kustomization.yaml, config/crd/patches/singleton_in_flowcollectors.yaml, config/samples/flows_v1alpha1_flowcollector.yaml
Using the validation scheme to only accept default as the CRD name, only one instance of the CRD can be created per cluster.
Jira link : https://issues.redhat.com/browse/NETOBSERV-82
=> NETOBSERV-82: Enforcing crd validation to only have one instance per cluster

config/samples/dashboards/Network Observability.json
This first dashboard shows:
- Volumetry per namespace
- Volumetry per workload
- Raw logs
=> NETOBSERV-40 Create grafana dashboard

controllers/flowcollector_controller_test.go, controllers/goflowkube/goflowkube_objects.go, controllers/goflowkube/goflowkube_reconciler.go, pkg/helper/testhelpers.go
* Tested HPA autoscaler
* Corrected bug in "autoScalerNeedsUpdate" function
Testing coverage is now 80%. See description of task https://issues.redhat.com/browse/NETOBSERV-92 for more information.
Read more at: https://issues.redhat.com/browse/NETOBSERV-80?focusedCommentId=19364614 and https://issues.redhat.com/browse/NETOBSERV-92
=> NETOBSERV-80: Increased testing of goflowkube reconciler (& bugfix)

README.md
this was missing
It points to our main doc around loki
I started also to add doc about the FlowCollector CR, however I wanted to auto-generate it ideally and created this JIRA in that purpose: https://issues.redhat.com/browse/NETOBSERV-91 , so just leaving a link to the sample file here, for the time being.
=> readme: add mention to loki

config/rbac/role.yaml, controllers/flowcollector_controller.go, controllers/flowcollector_controller_test.go, controllers/goflowkube/goflowkube_objects.go
- Adding a HostPort to the container specification in the DaemonSet
- Setting the proper RBAC permissions
- Enable the deployment in the master node
=> NETOBSERV-90: enable deployment as Daemonset

api/v1alpha1/flowcollector_types.go, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/rbac/role.yaml, controllers/consoleplugin/consoleplugin_reconciler.go, controllers/consoleplugin/consoleplugin_test.go, controllers/constants/constants.go, controllers/flowcollector_controller.go, controllers/flowcollector_controller_test.go, controllers/flowcollector_objects.go, controllers/goflowkube/goflowkube_reconciler.go, controllers/goflowkube/goflowkube_test.go, controllers/ovs/flowsconfig.go, controllers/suite_test.go
Added several fields in the CRD :
- namespace to deploy goflow-kube and console-plugin pods
- name and namespace of the CNO configmap
=> NETOBSERV-83 : Namespace configuration

controllers/flowcollector_controller_test.go, controllers/goflowkube/goflowkube_objects.go, controllers/goflowkube/goflowkube_reconciler.go, controllers/goflowkube/goflowkube_test.go
It adds a new annotation to the pods that contains a digest of the
the goflow-kube-config configmap contents. When that configmap changes,
the Pod template inside the Daemonset or Deployment is updated so
Kubernetes will force the update of the goflow-kube pods.
Demo:
https://user-images.githubusercontent.com/939550/143897920-5a794abc-4e2b-48e5-9598-cc27f5d0191f.mp4
=> NETOBSERV-88: restart pods on configmap change (bugfix)

api/v1alpha1/flowcollector_types.go, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, controllers/consoleplugin/consoleplugin_objects.go, controllers/consoleplugin/consoleplugin_reconciler.go, controllers/consoleplugin/consoleplugin_test.go, controllers/flowcollector_controller.go, controllers/flowcollector_controller_test.go, controllers/suite_test.go, docs/FlowCollector.md
Fetches the Loki URL from the FlowCollector and accordingly configures
the Network Console Plugin to receive such URL.
It also adds the optional `querierUrl` argument, that can be specified
if the Loki querier and ingester are in different hosts. `querierUrl`
has priority over `url`.
Related PR: https://github.com/netobserv/network-observability-console-plugin/pull/11
=> NETOBSERV-96: passing Loki URL to the plugin backend

controllers/goflowkube/goflowkube_objects.go
This change add sticky session to goflowkube based on the client IP.
Related Jira issue:
https://issues.redhat.com/browse/NETOBSERV-158
=> NETOBSERV-158: Added sticky session to goflow kube to fix template defs miss

api/v1alpha1/flowcollector_types.go, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/samples/flows_v1alpha1_flowcollector.yaml, controllers/goflowkube/goflowkube_objects.go, docs/FlowCollector.md
... and default to "TimeFlowEnd"
JIRA: https://issues.redhat.com/browse/NETOBSERV-174
Note: by making it configurable rather than forced to TimeFlowEnd, we allow having a workaround when Loki generates a lot of out-of-order inserts. This can happen in previous versions of Loki.
=> NETOBSERV-174 Make loki TimestampLabel configurable

Makefile
Without -coverpkg=./... option, code coverage is only done for the package beeing tested.
Before PR:
> total:														(statements)			41.5%
After:
> total:															(statements)			71.6%
=> NETOBSERV-92 : Fixing tests coverage and adding coverage-report targets

Dockerfile, Makefile, config/manager/kustomization.yaml, controllers/consoleplugin/consoleplugin_objects.go, controllers/consoleplugin/consoleplugin_reconciler.go, controllers/consoleplugin/consoleplugin_test.go, controllers/goflowkube/goflowkube_objects.go, controllers/goflowkube/goflowkube_reconciler.go, controllers/goflowkube/goflowkube_test.go, main.go, pkg/helper/helpers.go, pkg/helper/helpers_test.go
JIRA https://issues.redhat.com/browse/NETOBSERV-107
version information is added in several places:
- via kustomize, as label on the operator (manager) itself
- through build ldflags, to the main package, logged for information
(both in "make build" and "make image-build")
- in deployed components (goflow-kube and console plugin) as k8s label
(note that the version here is taken from the images defined in CR, which can
be different from the operator version)
- lastly, I updated the helper target `make create-sample` so that it can use a custom version from env
Use the VERSION env in make targets to set a specific version
(e.g. `VERSION="0.1.0-test" IMAGE_TAG_BASE="quay.io/jotak/network-observability-operator" make image-build image-push deploy`)
=> NETOBSERV-107 Add version information

controllers/consoleplugin/consoleplugin_objects.go, controllers/constants/constants.go, controllers/goflowkube/goflowkube_objects.go, controllers/goflowkube/goflowkube_test.go
This PR is part of [NETOBSERV-169](https://issues.redhat.com/browse/NETOBSERV-169) - Create index on FlowDirection
Changes:
- Send Loki labels to console `plugin backend`
- Added `FlowDirection`
Check https://github.com/netobserv/network-observability-console-plugin/pull/70
=> NETOBSERV-169 send labels to console plugin

Makefile, README.md, hack/deploy-grafana.sh
1. Updating the Makefile to allow deploy and undeploy of sample cr (there was some unneeded | etch command)
2. Adding Development documentation inside hack folder
3. Adding simple Loki deployment 
4. Adding simple Loki Grafana deployment script
=> hack: development using "make run" (with loki)

Makefile
`run` was defined in two places (identical)
=> Trivial, remove duplicated run target

.github/workflows/release.yml, Makefile, shortlived.Dockerfile
https://issues.redhat.com/browse/NETOBSERV-192
Add release github action (similar to the one in console plugin)
Also small changes in the short-lived image implementation, similar to
what was done  in FLP
=> NETOBSERV-192 automated release

.github/workflows/push_image_pr.yml, .github/workflows/rm-ok-to-test.yaml
Uses the 'ok-to-test' label to trigger the build/push
=> NETOBSERV-229 create pre-merge image on PR via action

config/samples/flows_v1alpha1_flowcollector_ebpf.yaml, controllers/ebpf/agent_controller.go, controllers/flowcollector_controller_ebpf_test.go
replaces manual comparison of fields by `equality.Semantic.DeepDerivative`, which skips fields of the "actual" state that are not in the "desired" state (e.g. these fields that are added by Kubernetes as metadata)
=> NETOBSERV-304: fix update reconciliation of eBPF agent

api/v1alpha1/flowcollector_types.go, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/samples/flows_v1alpha1_flowcollector.yaml, config/samples/flows_v1alpha1_flowcollector_ebpf.yaml, config/samples/flows_v1alpha1_flowcollector_versioned.yaml, controllers/flowlogspipeline/flp_objects.go, controllers/flowlogspipeline/flp_test.go, docs/FlowCollector.md
Use on each of the FLP instances: http://localhost:90990/metrics
For example::
```
1000650000@flowlogs-pipeline-hpjn4:/$ curl localhost:9090/metrics | grep "ingest_collector_flow_logs_processed"
ingest_collector_flow_logs_processed 2899
```
We see that we processed 2899 from the point in time we started the pod
=> Adding support for FLP operational metrics

controllers/flowlogspipeline/flp_objects.go
This PR in FLP sets prometheus as terminal stage: https://github.com/netobserv/flowlogs-pipeline/pull/194
This means that we need to update our definition in order to avoid breaking the installation when we push the master image of FLP.
=> FLP: use prometheus as terminal stage

api/v1alpha1/flowcollector_types.go, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/samples/flows_v1alpha1_flowcollector.yaml, config/samples/flows_v1alpha1_flowcollector_versioned.yaml, controllers/ebpf/agent_controller.go, controllers/ebpf/internal/permissions/permissions.go, controllers/flowcollector_controller_ebpf_test.go, docs/FlowCollector.md
It also allows configuring the agent to run with full capabilities as a fallback option for some Kubernetes distributions that do not recognize the `BPF` and `PERFMON` capabilities (documented here https://github.com/netobserv/netobserv-ebpf-agent/pull/23)
=> NETOBSERV-307: eBPF agent running with capabilities instead of full privileges

config/manifests/bases/netobserv-operator.clusterserviceversion.yaml
Missing `console.openshift.io/plugins` annotation
> An operator can also give console a hint that it has a plugin available through the console.openshift.io/plugins annotations. The annotation tells the console to show a checkbox to enable plugins during operator install. Only users who can edit the console operator config will see the checkbox. The annotation value is a serialized JSON array of strings, where each item is the name of a ConsolePlugin resource the operator will create.
https://github.com/openshift/enhancements/blob/master/enhancements/console/dynamic-plugins.md#delivering-plugins
=> Console plugin annotation

README.md, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/manifests/bases/netobserv-operator.clusterserviceversion.yaml, controllers/flowcollector_controller.go, controllers/flowcollector_controller_test.go, controllers/flowlogspipeline/flp_test.go
I noticed this while working on kafka but did not want to overload the kafka PR.
We still have naming reference to goflow instead of flp, this PR change them.
=> Removed goflow references

controllers/consoleplugin/consoleplugin_reconciler.go, controllers/flowlogspipeline/flp_reconciler.go, controllers/reconcilers/namespaced_objects_manager.go
The errors we see in the operator logs are due to trying to clean items from the previous namespace (in the case of a changing namespace), despite the context here is not a changing namespace.
So I just duplicated the cleanup function to allow cleaning the current namespace.
=> NETOBSERV-365 Fix errors in operator logs

.mk/local.mk
It was not officially supported by the operator, and now has been
removed from its config to avoid keeping unnecessary opened port
=> Remove netflow v5 load generator

controllers/flowlogspipeline/flp_objects.go, controllers/flowlogspipeline/flp_test.go
Wait for https://github.com/netobserv/flowlogs-pipeline/pull/226 before merge
This PR adds a `stdout` stage after enrichment when desired `logLevel` is `trace`
=> NETOBSERV-334 ebpf: flows are logged properly in FLP

.mk/development.mk, .mk/local.mk, .mk/ocp.mk, .mk/sample.mk
The workload is based on GoogleCloudPlatform/microservices-demo
Syn attack is based on docker and an example from https://github.com/bilalcaliskan/syn-flood
=> add example workload (with syn attack)

config/samples/flows_v1alpha1_flowcollector.yaml, config/samples/flows_v1alpha1_flowcollector_versioned.yaml, controllers/ebpf/agent_controller.go, controllers/flowcollector_controller_ebpf_test.go, controllers/flowlogspipeline/flp_reconciler.go, controllers/flowlogspipeline/flp_test.go, controllers/suite_test.go
This PR requires that the following PR is first merged: https://github.com/netobserv/netobserv-ebpf-agent/pull/33
When Kafka and the eBPF agent are set:
* It deploys the eBPF agent configured to export directly to kafka
* It does not deploy the flowlogs-processor-ingester daemonset.
=> NETOBSERV-258: configure eBPF agent for Kafka

README.md, config/manifests/bases/netobserv-operator.clusterserviceversion.yaml
"The provided eBPF Agent" was ambiguous, it is not clear if it's provided
by NetObserv or by the user.
=> Doc: remove ambiguity

config/samples/dashboards/Network Observability.json
This removes the extraneous "Row title" dashboard that shouldn't be there. It fixes it so the "Logs" dashboard shows up.
=> NETOBSERV-297: Some Grafana dashboards are not showing up

controllers/consoleplugin/consoleplugin_objects.go
This is necessary to add a ServiceMonitor for cluster monitoring
=> Give a name to console plugin service port

api/v1alpha1/flowcollector_types.go, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, controllers/consoleplugin/consoleplugin_objects.go, controllers/consoleplugin/consoleplugin_test.go, controllers/flowlogspipeline/flp_objects.go, docs/FlowCollector.md, go.mod, go.sum, vendor/github.com/prometheus/common/config/http_config.go, vendor/modules.txt
Following conversation with @memodi, this PR force skip TLS checks on both FLP & console plugin until implementation and allow configuration of Loki tenant ID
=> NETOBSERV-309 skip TLS checks & add TenantID

Makefile
Sometimes we had to run "generate" and/or "manifest" make targets twice
in order to have the doc generated. This should fix it.
Also, use the existing go-get-tool function to get crdoc, to unify with
existing tooling download method
=> Fix issues with doc/code/manifest generation

api/v1alpha1/flowcollector_types.go, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/samples/flows_v1alpha1_flowcollector.yaml, controllers/flowlogspipeline/flp_objects.go, controllers/flowlogspipeline/flp_reconciler.go, controllers/flowlogspipeline/flp_test.go, docs/FlowCollector.md, pkg/filters/field_filter.go
When using IPFIX, it's now possible to avoid storing lots of garbage by
turning dropUnusedFields to true (it actually defaults to true)
I saw about 30% less space used with this method, uncompressed (it's probably less with compression)
=> NETOBSERV-182 Drop unused fields

api/v1alpha1/flowcollector_types.go, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/samples/flows_v1alpha1_flowcollector.yaml, controllers/flowcollector_controller_test.go, controllers/ovs/flowsconfig_cno_reconciler.go, controllers/ovs/flowsconfig_ovnk_reconciler.go, controllers/ovs/flowsconfig_types.go, docs/FlowCollector.md
By default, prevent setting sampling=1 for IPFIX ~~(automatically raised
to 2 in that case)~~
Flag "forceSampleAll" can be use to force sampling=1 (used at their own risks)
See bugs:
- https://bugzilla.redhat.com/show_bug.cgi?id=2103136
- https://bugzilla.redhat.com/show_bug.cgi?id=2104943
Change ipfix cache defaults:
- timeout decreased to 20s
- max-flows increased to 400
=> Workaround for sampling=1 bugs

controllers/flowcollector_controller_console_test.go, controllers/flowcollector_controller_ebpf_test.go, controllers/flowcollector_controller_test.go, controllers/flowlogspipeline/flp_objects.go
Flaky tests are due to the new status conditions recently added to the CRD: the CR kinda auto-updates its status and could cause a race when tests also update the CR in the meantime, resulting in this error message: "the object has been modified; please apply your changes to the latest version and try again"
To fix that, this patch provide a new idiomatic way to update CR in
tests, where it will first fetch the current CR until it is ready
(assuming than its status won't change "by itself" once it's ready)
=> Try fix flaky tests, + use filepath.Join

Makefile
Use 'go install' to install the executable. This stopped working in  
go1.18 because of https://go.dev/doc/go-get-install-deprecation.
In making this change, kustomize broke and no longer installed. The problem  
is documented in kubernetes-sigs/kustomize#3618.  
The solution is to use at least v4.5.2. kustomize was upgraded to 4.5.7  
from 3.8.8 and everything still worked.
=> NETOBSERV-505 NOO fails to build with go1.18 and above

api/v1alpha1/flowcollector_types.go, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, docs/FlowCollector.md
Align sample file / CSV with kubebuilder / CRD, using 9102
=> Use consistent default prom port

api/v1alpha1/flowcollector_types.go, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, controllers/consoleplugin/consoleplugin_objects.go, controllers/flowlogspipeline/flp_objects.go, docs/FlowCollector.md, pkg/helper/tokens.go
This PR adds `sendAuthToken` option to configure the following components to send their service account token as Authorization header:
- [flowlogs-pipeline](https://github.com/netobserv/flowlogs-pipeline/pull/260)
- [console-plugin](https://github.com/netobserv/network-observability-console-plugin/pull/183)
It will need [skip TLS checks & add TenantID](https://github.com/netobserv/network-observability-operator/pull/120) ~~and [flowlogs-pipeline](https://github.com/netobserv/flowlogs-pipeline/pull/260)~~ to be merged first
Edit, following @OlivierCazade feedback we can directly set `flowlogs-pipeline` `clientConfig.authorization` and keep `loki-client-go` as is.
=> NETOBSERV-101 R&D: Kube enricher write path for downstream operator

README.md, api/v1alpha1/flowcollector_types.go, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/manifests/bases/netobserv-operator.clusterserviceversion.yaml, docs/FlowCollector.md
Add a few comments+link about why using kafka
=> Remove kafka experimental flag for next release

api/v1alpha1/flowcollector_types.go, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, controllers/consoleplugin/consoleplugin_objects.go, controllers/consoleplugin/consoleplugin_reconciler.go, docs/FlowCollector.md
Following https://github.com/observatorium/api/pull/350 we will not have access to loki ready, config, metrics and build infos endpoints using the gateway.
This PR allow to configure a `statusURL` in the CRD and send it to the console plugin
Related PR: https://github.com/netobserv/network-observability-console-plugin/pull/186
=> NETOBSERV-101 - loki statusURL

README.md, api/v1alpha1/flowcollector_types.go, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/manifests/bases/netobserv-operator.clusterserviceversion.yaml, config/samples/flows_v1alpha1_flowcollector.yaml, docs/FlowCollector.md
- Default agent is eBPF
- Default eBPF sampling is 50
- Update doc to align with these changes
- Add more hints in doc about sampling
- In doc's troubleshooting, stop mentioning the workarounds for
openshift 4.8 / 4.9: they'll be obsolete when we remove the Deployment
kind option for FLP
- Add a couple of troubleshooting info
=> NETOBSERV-467 Updated defaults (eBPF / sampling), update doc

api/v1alpha1/flowcollector_types.go, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, docs/FlowCollector.md
I set some minimalist resources spec for eBPF agent as already defined for others components.
This works fine on my dev cluster generating some spam on a httpd deployment:
- memory is around 30MiB
- max cpu at 84m 
Another discussion around what limits should be set for downstream is available in [NETOBSERV-380](https://issues.redhat.com/browse/NETOBSERV-380)
Requests / limits per cluster size should be documented for upstream in [NETOBSERV-493](https://issues.redhat.com/browse/NETOBSERV-493)
=> NETOBSERV-435 - Set default req/limits resources for eBPF agent

config/samples/flows_v1alpha1_flowcollector.yaml
(it makes it easier to tune these limits by modifying the CR)
side question: should we change these limit? E.g. raise to, maybe, 800 Mi ?
=> Add default limits to CR

.mk/local.mk, .mk/ocp.mk, DEVELOPMENT.md, Makefile, README.md, api/v1alpha1/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, bundle/manifests/netobserv-manager-config_v1_configmap.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/default/kustomization.yaml, config/manager/kustomization.yaml, config/manifests/bases/netobserv-operator.clusterserviceversion.yaml, config/samples/flows_v1alpha1_flowcollector.yaml, config/samples/flows_v1alpha1_flowcollector_versioned.yaml, controllers/consoleplugin/consoleplugin_objects.go, controllers/consoleplugin/consoleplugin_test.go, controllers/constants/constants.go, controllers/ebpf/agent_controller.go, controllers/ebpf/internal/permissions/permissions.go, controllers/flowcollector_controller_console_test.go, controllers/flowcollector_controller_ebpf_test.go, controllers/flowcollector_controller_test.go, docs/FlowCollector.md, hack/deploy-grafana.sh, main.go
- Use "netobserv" instead of "network-observability" (e.g. as default namespace)
Other required PRs:
- console: https://github.com/netobserv/network-observability-console-plugin/pull/191
- docs: https://github.com/netobserv/documents/pull/26
=> NETOBSERV-433 and NETOBSERV-373 - unify names

.mk/sample.mk
In the current implementation, there are no sufficient privileges to deploy the demo workload. This PR adds privileged scc to the default serviceaccount under the namespace sample-workload
=> Fix scc for sample-workload

api/v1alpha1/flowcollector_types.go, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/samples/flows_v1alpha1_flowcollector.yaml, controllers/flowlogspipeline/flp_objects.go, docs/FlowCollector.md
Related PR: https://github.com/netobserv/flowlogs-pipeline/pull/308
=> Allow enabling profiler port in FLP

controllers/flowlogspipeline/flp_objects.go
This PR needs to be merged together with https://github.com/netobserv/netobserv-ebpf-agent/pull/55
To make/test changes incrementally, FLP Kafka communication is via Protobuf when receiving data from eBPF but still JSON in IPFIX mode.
After this PR, I will fix FLP to produce correct protobuf messages and then make this option by default here.
=> NETOBSERV-589: setup FLP transformer to receive protobuf for eBPF mode

api/v1alpha1/flowcollector_types.go, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/samples/flows_v1alpha1_flowcollector.yaml, controllers/ebpf/agent_controller.go, controllers/flowlogspipeline/flp_transfo_objects.go, docs/FlowCollector.md
Follow-up on https://github.com/netobserv/flowlogs-pipeline/pull/309
- PullQueueCapacity: capacity of the kafka consumer client internal
queue
- PullMaxBytes: indicates to the broker the maximum batch size that the consumer will accept.
**Update**
[Add producerBatchSize, add metric, tweak defaults](https://github.com/netobserv/network-observability-operator/pull/170/commits/3fc9186b02f61ca405f036b590cb7f0b9f364b1d)
[3fc9186](https://github.com/netobserv/network-observability-operator/pull/170/commits/3fc9186b02f61ca405f036b590cb7f0b9f364b1d)
New metric "bandwidth_per_namespace" allows to get flows sizes (ie.
extracted Bytes sum) per source and dest namespace
That proves useful for self-monitoring, eg. to get the overhead of
netobserv's traffic compared to the rest of the traffic.
Also, …
=> Expose new Kafka parameters + tweak defaults

api/v1alpha1/flowcollector_types.go, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/samples/flows_v1alpha1_flowcollector.yaml, controllers/consoleplugin/consoleplugin_objects.go, controllers/flowlogspipeline/flp_common_objects.go, docs/FlowCollector.md
This PR enable the new option from the console from this PR:
https://github.com/netobserv/network-observability-console-plugin/pull/198
=> NETOBSERV-489: Use authorize feature from console plugin API

api/v1alpha1/flowcollector_types.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/samples/flows_v1alpha1_flowcollector.yaml, controllers/consoleplugin/consoleplugin_reconciler.go, controllers/consoleplugin/consoleplugin_test.go, controllers/flowcollector_controller_console_test.go, controllers/flowcollector_controller_test.go, controllers/flowlogspipeline/flp_test.go, controllers/flowlogspipeline/flp_transfo_reconciler.go, docs/FlowCollector.md
This add a status field in HPA section to deploy or not HPA.
At some point in the future we may want a third option: not deploying the HPA but also not reconciling pod count so an external HPA can be used.
=> NETOBSERV-382: Added status field in HPA configuration

controllers/ebpf/internal/permissions/permissions.go
Openshift 4.12 was missing some SCC-related annotations in the netobserv-privileged namespace and couldn't properly deploy the eBPF agent daemonset.
=> NETOBSERV-694: add missing annotations to netobserv-privileged namespace

controllers/consoleplugin/consoleplugin_objects.go, controllers/ebpf/agent_controller.go, controllers/flowcollector_controller_ebpf_test.go, controllers/flowcollector_controller_test.go, controllers/flowlogspipeline/flp_common_objects.go, pkg/helper/helpers.go, pkg/helper/helpers_test.go
Using downstream images prevents the flowcollector from being deployed as they use very long sha digests for the version.
=> NETOBSERV-707: cut image version labels > 63 chars

controllers/flowlogspipeline/flp_test.go, controllers/flowlogspipeline/metrics_definitions/namespace_flows_total.yaml
E.g. to get netobserv flows in percentage of total:
```
100 * (sum (rate(netobserv_namespace_flows_total{SrcK8S_Namespace="netobserv"}[1m])) + sum (rate(netobserv_namespace_flows_total{SrcK8S_Namespace!="netobserv", DstK8S_Namespace="netobserv"}[1m]))) / sum (rate(netobserv_namespace_flows_total[1m]))
```
=> NETOBSERV-712 Add metric to measure number of flows per namespace

DEVELOPMENT.md, Makefile, api/v1alpha1/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/crd/kustomization.yaml, config/crd/patches/version_in_flowcollectors.yaml, config/crd/patches/version_in_flowcollectors_envtpl.yaml, config/default/manager_auth_proxy_patch.yaml, config/manager/manager.yaml, config/samples/flows_v1alpha1_flowcollector.yaml, config/samples/flows_v1alpha1_flowcollector_versioned.yaml, controllers/ebpf/agent_controller.go, controllers/flowcollector_controller.go, controllers/flowcollector_controller_ebpf_test.go, controllers/operator/config.go, controllers/suite_test.go, docs/FlowCollector.md, main.go
From "[Best Practices](https://docs.engineering.redhat.com/display/CFC/Best_Practices)" document:
> Images to be used for operands MUST be in the relatedImages field and SHOULD be in environment variables to the operator.
As an initial test, I'm moving first only one image to evaluate how will it work with CPaaS. Once we succeed, we will move the rest of images.
=> NETOBSERV-690 (spike): move eBPF image pullspec from CRD to CSV

.mk/local.mk, .mk/ocp.mk, .mk/sample.mk
- Fix the sample by pinning it to a specific version (4.1)
- Adding required parameters to run operator command (from the command line)
=> fix make run (ocp and local)

go.mod, main.go, vendor/modules.txt
Changed timestamps in epoch milliseconds by something like `2022-12-01T09:53:35.484Z`.
=> NETOBSERV-693: use ISO8601 for logging timestamps

.github/workflows/pull_request.yml, Makefile, bundle.Dockerfile, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/manager/manager.yaml, config/manifests/bases/description-ocp.md, config/samples/flows_v1alpha1_flowcollector_versioned.yaml
Requires https://github.com/netobserv/network-observability-operator/pull/200
The bundle process needs to work both for upstream and downstream
Every time someone changes something that would alter the bundle (e.g.
CSV description), they should run "make bundle" (with no options)
It will generate the CSV with injected upstream description.
The downstream description will be updated too, but not injected: this
step will be done later on, in midstream.
=> NETOBSERV-727 Update bundle process

README.md
I tested and confirmed that the bug come from the kafka-go dependency.
I am trying to fix it and I opened a bug report in the library side.
Meanwhile for GA, I think it is better to document the workaround.
=> NETOBSERV-672: Document bug when flowcollector is deployed before kafka

.github/workflows/pull_request.yml, .github/workflows/push_image.yml, .github/workflows/push_image_pr.yml, .github/workflows/release.yml, Dockerfile
Backport of https://github.com/netobserv/network-observability-operator/pull/217
=> Bug NETOBSERV-743: update build image & CI tests to Go 1.18 (backport to 4.12)

Makefile, api/v1alpha1/flowcollector_types.go, bundle.Dockerfile, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/samples/flows_v1alpha1_flowcollector.yaml, config/samples/flows_v1alpha1_flowcollector_versioned.yaml, docs/FlowCollector.md
- add some explanation about agent's privileged mode
- add some hints when configuring kafka & TLS
- add some hints about mTLS
- remove IPFIX from the sample CR (it still exists but wouldn't show up as the sample CR when installing from OLM console)
- remove a couple of other much unused fields from the sample CR
=> CRD doc update - simplified sample

.golangci.yml, Makefile
Backport of https://github.com/netobserv/network-observability-operator/pull/227
=> Update golangci-lint (release-4.12)

Makefile, api/v1alpha1/flowcollector_types.go, bundle.Dockerfile, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/samples/flows_v1alpha1_flowcollector.yaml, config/samples/flows_v1alpha1_flowcollector_versioned.yaml, docs/FlowCollector.md
Backport of https://github.com/netobserv/network-observability-operator/pull/224
* CRD doc update - simplified sample
- add some explanation about agent's privileged mode
- add some hints when configuring kafka & TLS
- add some hints about mTLS
- remove IPFIX from the sample CR (it still exists but wouldn't show up as the sample CR when installing from OLM console)
- remove a couple of other much unused fields from the sample CR
* update operator-sdk default version
=> [4.12 backport] CRD doc update - simplified sample (#224)

bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/manager/manager.yaml
- Remove CPU limit
- Set memory limit to 400MiB
=> NETOBSERV-730 Change operator limits

Makefile, api/v1alpha1/flowcollector_types.go, api/v1alpha1/zz_generated.deepcopy.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/default/manager_auth_proxy_patch.yaml, config/manifests/bases/netobserv-operator.clusterserviceversion.yaml, controllers/consoleplugin/consoleplugin_objects.go, controllers/consoleplugin/consoleplugin_reconciler.go, controllers/consoleplugin/consoleplugin_test.go, controllers/flowcollector_controller.go, controllers/flowcollector_controller_console_test.go, controllers/flowcollector_controller_test.go, controllers/flowlogspipeline/flp_test.go, controllers/flowlogspipeline/flp_transfo_objects.go, controllers/flowlogspipeline/flp_transfo_reconciler.go, controllers/suite_test.go, docs/FlowCollector.md, main.go
Backport of https://github.com/netobserv/network-observability-operator/pull/226
=> NETOBSERV-750: fix to enable being in the 4.12 catalog (release-4.12 backport)

RELEASE.md
fwiw, upgrade path worked correctly without the previous hack
=> update upstream release doc

bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/manager/manager.yaml
- Remove CPU limit
- Set memory limit to 400MiB
=> [4.12 backport] NETOBSERV-730 Change operator limits (#229)

FAQ.md
Added mention on how to check and restart console pods to clear plugin cache
=> NETOBSERV-704 Netflow traffic page doesn't appear sometimes

docs/QuickFilters.md
[edit] I changed my approach, instead of adding new filters directly in CR, some being a bit hacky, I prefer just to document them as examples. Users can copy-paste them in their CR
--- 
This filter shows cluster traffic to outside.
Note there's a trick by excluding source port 443, this is to remove traffic from of kind "ingress to outside" ie. the response traffic of an ingress connection. It's a bit hacky.
=> Quick filters: add some examples in documentation

bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/manifests/bases/description-ocp.md, config/manifests/bases/description-upstream.md
Suggesting to backport this fix, as the typos show up in the Operator description in operatorhub
=> [4.12] [doc] Fix typos in CSV desc (#244)

controllers/consoleplugin/consoleplugin_objects.go, controllers/consoleplugin/consoleplugin_reconciler.go, controllers/consoleplugin/consoleplugin_test.go, controllers/constants/constants.go, controllers/flowcollector_controller_test.go, controllers/flowlogspipeline/flp_common_objects.go, controllers/flowlogspipeline/flp_ingest_reconciler.go, controllers/flowlogspipeline/flp_monolith_reconciler.go, controllers/flowlogspipeline/flp_reconciler.go, controllers/flowlogspipeline/flp_test.go, controllers/flowlogspipeline/flp_transfo_reconciler.go, controllers/ovs/flowsconfig_ovnk_reconciler.go, controllers/reconcilers/client_helper.go, pkg/helper/comparators.go
- Both for console plugin and FLP, need to check whether volumes changes in reconcile loop
- Some refactoring to share common comparison functions
- Remove namespace comparisons in several places because they are handled differently (namespace changes doesn't trigger the usual workload updates, it deletes all / recreate all)
- Add some tests
=> NETOBSERV-772 check volume change in reconcile loop

api/v1alpha1/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, controllers/flowcollector_controller_ebpf_test.go, docs/FlowCollector.md, docs/flowcollector-flows-netobserv-io-v1alpha1.adoc
* NETOBSERV-691 better document cacheMaxFlows/Timeout (in CRD)
* Update asciidoc
* Fix missing period
* fix flaky test
=> [1.1 backport] NETOBSERV-691 better document cacheMaxFlows/Timeout (in CRD) (#255)

bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/samples/flows_v1alpha1_flowcollector.yaml, config/samples/flows_v1alpha1_flowcollector_versioned.yaml
Changing to "loki-gateway-ca-bundle" so that it matches loki operator 5.6 name
JIRA: https://issues.redhat.com/browse/NETOBSERV-793
=> NETOBSERV-793 Change default loki CA configmap name

bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/samples/flows_v1alpha1_flowcollector.yaml, config/samples/flows_v1alpha1_flowcollector_versioned.yaml
Changing to "loki-gateway-ca-bundle" so that it matches loki operator 5.6 name
Backport of https://github.com/netobserv/network-observability-operator/pull/254
=> NETOBSERV-793 [1.2 backport] Change default loki CA configmap name (#254)

bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/flowcollector_controller.go, controllers/flowlogspipeline/flp_common_objects.go, controllers/flowlogspipeline/flp_ingest_reconciler.go, controllers/flowlogspipeline/flp_monolith_reconciler.go, controllers/flowlogspipeline/flp_test.go, controllers/flowlogspipeline/flp_transfo_reconciler.go, pkg/helper/comparators.go
This PR add support for PrometheusRule to configure different alerts.
I also added change detection to service monitor which for now, once created, is not checked.
=> NETOBSERV-674 : Added management of prometheus rule

controllers/consoleplugin/consoleplugin_objects.go
I just realized that I forgot to push the last commit on my previous PR.
This was linked to PR comments to make namespace configuration.
=> NETOBSERV-674: Added alertNamespaces field in console plugin frontend configuration

bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/manifests/bases/netobserv-operator.clusterserviceversion.yaml
update operator capability to `Seamless Upgrades`
guidelines https://sdk.operatorframework.io/docs/overview/operator-capabilities/#level-2---seamless-upgrades
=> NETOBSERV-896: update operator capability

controllers/consoleplugin/consoleplugin_reconciler.go, controllers/consoleplugin/consoleplugin_test.go, controllers/flowlogspipeline/flp_ingest_reconciler.go, controllers/flowlogspipeline/flp_monolith_reconciler.go, controllers/flowlogspipeline/flp_test.go, controllers/flowlogspipeline/flp_transfo_reconciler.go, pkg/helper/change_report.go, pkg/helper/comparators.go
The infinite reconcile was due to a bad change comparison of liveness/readiness probes.
This commit is also adding better reconciliation change tracking utility for debugging.
=> NETOBSERV-856 Fix infinite reconcile & add more debugging utility

DEVELOPMENT.md, Makefile, RELEASE.md
When using makefile commands, operator-sdk now is downloaded to bin; not all docs were updated when this change was made, fixing it
=> Fix doc for operator-sdk command & make generate now must be explicit

api/v1alpha1/flowcollector_types.go, api/v1beta1/flowcollector_types.go, controllers/consoleplugin/consoleplugin_objects.go, controllers/consoleplugin/consoleplugin_reconciler.go, controllers/consoleplugin/consoleplugin_test.go, controllers/ebpf/agent_controller.go, controllers/flowlogspipeline/flp_common_objects.go, controllers/flowlogspipeline/flp_ingest_objects.go, controllers/flowlogspipeline/flp_ingest_reconciler.go, controllers/flowlogspipeline/flp_monolith_objects.go, controllers/flowlogspipeline/flp_monolith_reconciler.go, controllers/flowlogspipeline/flp_test.go, controllers/flowlogspipeline/flp_transfo_objects.go, controllers/flowlogspipeline/flp_transfo_reconciler.go, controllers/ovs/flowsconfig_cno_reconciler.go, controllers/ovs/flowsconfig_ovnk_reconciler.go, pkg/helper/flowcollector.go
Added sampling field to configuration.
To do that I needed to keep a reference to the FlowCollectorSpec object in the console object builder so I added a bit of refactoring to only keep this object and remove ConsolePlugin and Loki reference which are not needed anymore.
=> NETOBSERV-155: Added sampling field to console frontend configuration

controllers/ovs/flowsconfig_ovnk_reconciler.go
Exit silently when ovn-k workloads aren't found, when they are not required
=> Fix deployment on non-ovnk (e.g. kind)

DEVELOPMENT.md, Makefile
In https://github.com/netobserv/network-observability-operator/pull/274 the way IMG is used is changed, which broke deploying all latest components
This patch introduces a new "deploy-latest" target to explicitly deploy all components on their `main` branches
=> Fix regression on deploying latest

.mk/development.mk, DEVELOPMENT.md, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/rbac/role.yaml, controllers/flowcollector_controller.go, controllers/flowcollector_objects.go, controllers/operator/config.go, controllers/reconcilers/client_helper.go, controllers/suite_test.go, main.go
Add downstream configuration boolean.
To override this boolean run: `make set-release-kind-downstream`
This PR does not change the HTTPS config for the operator metrics endpoint but I did not want to overload the PR, I will do another PR about it.
=> NETOBSERV-736: Added downstream deployment configuration for monitoring collection

.mk/ocp.mk, controllers/flowcollector_controller.go, controllers/flowlogspipeline/flp_common_objects.go, controllers/flowlogspipeline/flp_monolith_objects.go, controllers/flowlogspipeline/flp_monolith_reconciler.go, controllers/flowlogspipeline/flp_reconciler.go, controllers/flowlogspipeline/flp_test.go, controllers/flowlogspipeline/flp_transfo_objects.go, controllers/flowlogspipeline/flp_transfo_reconciler.go, controllers/flowlogspipeline/metrics_definitions/namespace_flows_total.yaml, controllers/flowlogspipeline/metrics_definitions/node_egress_bytes_total.yaml, controllers/flowlogspipeline/metrics_definitions/node_ingress_bytes_total.yaml, controllers/flowlogspipeline/metrics_definitions/workload_egress_bytes_total.yaml, controllers/flowlogspipeline/metrics_definitions/workload_egress_packets_total.yaml, controllers/flowlogspipeline/metrics_definitions/workload_ingress_bytes_total.yaml, controllers/flowlogspipeline/metrics_definitions/workload_ingress_packets_total.yaml, pkg/discover/apis.go
Take grafana dashboards created by flp confgenerator [https://github.com/netobserv/flowlogs-pipeline/pull/369] and insert them in the Openshift console.
It is required to first merge FLP PR369, then update go.mod, go mod vendor, etc, and then to merge this PR.
=> Grafana dashboards

.github/workflows/pull_request.yml, DEVELOPMENT.md, Makefile, bundle/manifests/netobserv-operator.clusterserviceversion.yaml
After the recent reworking on the Makefile, there were still some pending issues. E.g. we introduced a "deploy-latest" target but it did not allow to override the operator image.
This is rollbacking part of the last changes:
- deploy-latest is removed, we can run "make deploy" as we used to do before
- make deploy now uses again "main" images by default, as before
- keeping the behaviour that Mohamed introduced, "make bundle" keeps using the provided IMG
- UNLIKE before: running "make bundle" alone will NOT update the bundle so it is ready for commit; For that, a new target "make update-bundle" is introduced
- "make bundle" does not generate the creation date as it used to do. This is now done via "make bundle-build". It means that release scripts have to be updated so they generate the …
=> Fix remaining Makefile issues + annoying bundle date

.github/workflows/pull_request.yml, controllers/consoleplugin/consoleplugin_reconciler.go, controllers/flowcollector_controller.go, controllers/flowcollector_controller_console_test.go, controllers/flowcollector_controller_test.go, controllers/flowlogspipeline/flp_ingest_reconciler.go, controllers/flowlogspipeline/flp_monolith_reconciler.go, controllers/flowlogspipeline/flp_reconciler.go, controllers/flowlogspipeline/flp_test.go, controllers/flowlogspipeline/flp_transfo_reconciler.go, controllers/reconcilers/namespaced_objects_manager.go, controllers/suite_test.go, pkg/discover/apis.go, pkg/helper/comparators.go, test-assets/prometheusrule.yaml, test-assets/servicemonitors.yaml
bug tld;dr: 
We need to be careful about not tying lifecycle of different objects together, as this would be assuming a certain state, which creates "holes" in the reconcile logic - we must avoid as much as possible any assumption about the current state
=> NETOBSERV-909 fix servicemonitor & prom rule reconcile

api/v1alpha1/flowcollector_webhook.go, api/v1alpha1/zz_generated.conversion.go, api/v1beta1/flowcollector_types.go, api/v1beta1/zz_generated.deepcopy.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/samples/flows_v1beta1_flowcollector.yaml, config/samples/flows_v1beta1_flowcollector_versioned.yaml, controllers/consoleplugin/consoleplugin_objects.go, controllers/constants/constants.go, controllers/flowcollector_controller_test.go, controllers/flowlogspipeline/flp_common_objects.go, controllers/flowlogspipeline/flp_test.go, docs/FlowCollector.md, pkg/helper/flowcollector.go
`outputRecordTypes` -> `logTypes`
`connection` -> `conversation`
```yaml
spec:
...
processor:
...
logTypes: FLOWS
conversationHeartbeatInterval: 30s
conversationEndTimeout: 10s
```
Let's merge this first for consistency (at user level) and see if we do the renaming in FLP component in a followup since there are lots of changes
=> NETOBSERV-928 Connection tracking renaming

controllers/flowcollector_controller.go, controllers/flowcollector_controller_test.go, controllers/flowcollector_objects.go, controllers/flowlogspipeline/flp_common_objects.go, controllers/infra_health_dashboard.json, controllers/reconcilers/client_helper.go
This PR add infra health dashboard.
I first try to generate the dashboard using FLP confgen but I faced multiple limitations:
- Not possible to use `rows` definitions to have multiple foldable subsections
- Not possible to have multiple query on the same graph. Here I wanted to have ingested flows and sent to loki flows in the same graph
- Not possible to manage graph width so we can have mulitple graphs on the same row. Here for CPU and memory utilization.
You can check [this branch](https://github.com/OlivierCazade/network-observability-operator/tree/health-dashboard-flp-api) which is working on how it was using FLP confgen.
If at some point we have to update this dashboard too often. We may want to implement this limitations in FLP confgen and use it.
=> NETOBSERV-123: Added infra health dashboard

controllers/flowlogspipeline/flp_common_objects.go
This PR is a follow up on:
https://github.com/netobserv/flowlogs-pipeline/pull/391
=> Enable TCP flags handling in FLP

api/v1alpha1/flowcollector_types.go, api/v1beta1/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, controllers/flowcollector_controller_console_test.go
since we have now a release out with v1beta1, its time to make `v1beta1` as the storage apis version
tested on OCP cluster
```
oc get flowcollectors
NAME      AGENT   SAMPLING (EBPF)   DEPLOYMENT MODEL   STATUS
cluster   EBPF    50                DIRECT             Ready
```
=> NETOBSERV-904: Make v1beta1 the storage version

controllers/consoleplugin/consoleplugin_objects.go, controllers/consoleplugin/consoleplugin_reconciler.go, controllers/consoleplugin/consoleplugin_test.go, controllers/ebpf/agent_controller.go, controllers/flowcollector_controller.go, controllers/flowcollector_controller_test.go, controllers/flowlogspipeline/flp_common_objects.go, controllers/flowlogspipeline/flp_ingest_objects.go, controllers/flowlogspipeline/flp_ingest_reconciler.go, controllers/flowlogspipeline/flp_monolith_objects.go, controllers/flowlogspipeline/flp_monolith_reconciler.go, controllers/flowlogspipeline/flp_test.go, controllers/flowlogspipeline/flp_transfo_objects.go, controllers/flowlogspipeline/flp_transfo_reconciler.go, controllers/reconcilers/client_helper.go, pkg/helper/certificates.go
Reverting most of certificate watching ([NETOBSERV-684](https://issues.redhat.com//browse/NETOBSERV-684)) as it generates a lot of pods restart.
We did not necessarily have to do this certificate watching as CM/secrets are updated within volumes.
We might however monitor carefully if new (or old) problems arise, potentially due to the kubelet sync delay for updating volumes
And also make sure certificates aren't cached in our different workloads
=> NETOBSERV-963 revert most of cert watching

controllers/consoleplugin/consoleplugin_objects.go
This fix avoid the case when empty cert paths are provided to console plugin making it crash:
```
- '-loki-status-ca-path'
- /var/loki-status-certs-ca/service-ca.crt
- '-loki-status-user-cert-path'
- ''
- '-loki-status-user-key-path'
- '' 
```
Set **tls: true** without using **statusUrl** to reproduce this error
=> NETOBSERV-844 skip empty cert paths

docs/flows-format.adoc, hack/asciidoc-flows-gen.sh
Just an asciidoc refresh after https://github.com/netobserv/network-observability-console-plugin/pull/321
=> Update json doc

.github/workflows/push_image.yml, Makefile, hack/test-workflow.sh
Hey,
There's been a bunch of regressions lately because of changes in the makefile and/or workflow, so I've written some "tests" around that. They don't yet cover everything I want (e.g. they should also cover everything that is documented in `RELEASE.md` and `DEVELOPMENT.md`)
=> Add workflow test hack

api/v1alpha1/flowcollector_types.go, api/v1beta1/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/samples/flows_v1alpha1_flowcollector.yaml, config/samples/flows_v1beta1_flowcollector.yaml, docs/FlowCollector.md
Re-enabling the defaults, so that the related dashboard is visible by default
=> NETOBSERV-993 Restore default metrics

api/v1beta1/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, controllers/consoleplugin/consoleplugin_objects.go, controllers/consoleplugin/consoleplugin_reconciler.go, controllers/consoleplugin/consoleplugin_test.go, controllers/flowlogspipeline/flp_common_objects.go, controllers/flowlogspipeline/flp_ingest_objects.go, controllers/flowlogspipeline/flp_ingest_reconciler.go, controllers/flowlogspipeline/flp_monolith_objects.go, controllers/flowlogspipeline/flp_monolith_reconciler.go, controllers/flowlogspipeline/flp_test.go, controllers/flowlogspipeline/flp_transfo_objects.go, controllers/flowlogspipeline/flp_transfo_reconciler.go, controllers/reconcilers/namespaced_objects_manager.go, docs/FlowCollector.md
Add missing CA/Secret to the console plugin service monitor
Cf https://github.com/netobserv/network-observability-console-plugin/pull/315
We might also want to add a bearer token config
=> NETOBSERV-765 Add CA/Secret config to ServiceMonitor

.mk/development.mk, DEVELOPMENT.md, hack/swap-image-csv.sh
Make those scripts work for OLM as well
Need to provide CSV & NAMESPACE info, e.g:
`CSV=network-observability-operator.v1.2.0
NAMESPACE=openshift-netobserv-operator VERSION=test USER=jotak make set-plugin-image`
=> Improve script to replace images for OLM

OWNERS, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/manifests/bases/netobserv-operator.clusterserviceversion.yaml
The list hasn't been updated since the begining ... Need to credit new folks and remove former maintainer (Mario)
=> Update list of maintainers

config/openshift-olm/monitor.yaml, config/openshift/monitor.yaml
Add monitoring role to the bundle.
=> NETOBSERV-1003: Added monitoring role to bundle

.github/workflows/push_image.yml, .github/workflows/push_image_pr.yml, .github/workflows/release.yml, .mk/shortcuts.mk, DEVELOPMENT.md, Makefile, hack/test-workflow.sh
Shortlived images are now built from scratch, not from a base. (Same can be done later for bundle & catalog)
It simplifies the workflows especially with multiarch. We don't need anymore the "ci*" make targets.
Restore the SHA-builds on merged commits
Also make multiarch configurable, and only for merged commits, not per PR
=> Attempt to fix multiarch workflow

.mk/development.mk, controllers/flowlogspipeline/metrics_definitions/namespace_flows_total.yaml, controllers/flowlogspipeline/metrics_definitions/node_egress_bytes_total.yaml, controllers/flowlogspipeline/metrics_definitions/node_ingress_bytes_total.yaml, controllers/flowlogspipeline/metrics_definitions/workload_egress_bytes_total.yaml, controllers/flowlogspipeline/metrics_definitions/workload_egress_packets_total.yaml, controllers/flowlogspipeline/metrics_definitions/workload_ingress_bytes_total.yaml, controllers/flowlogspipeline/metrics_definitions/workload_ingress_packets_total.yaml
- Fix metrics aggregations by using sum...by
- Do not split by FLP pod reporter as it's an implementation detail
1.3 backport: https://github.com/netobserv/network-observability-operator/pull/358
=> NETOBSERV-1005 dashboard: use sum...by

pkg/helper/comparators.go
use DeepDerivative on labels & annotations only, rather than full ObjectMeta
=> NETOBSERV-1076 Fix service change detection

pkg/helper/comparators.go
use DeepDerivative on labels & annotations only, rather than full ObjectMeta
=> NETOBSERV-1076 Fix service change detection [1.3 backport]

api/v1beta1/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/manifests/bases/netobserv-operator.clusterserviceversion.yaml, docs/FlowCollector.md, docs/flowcollector-flows-netobserv-io-v1beta1.adoc, hack/asciidoc-gen.sh
- clarify "deprecated" and "unsupported" features
- fix/remove a forgotten mention that kafka export is experimental
- reformulate the API description (it also appears on the CSV/operator description)
- a couple of minor fixes
- regenerate docs, update asciidoc
=> CRD doc updates

config/samples/flows_v1beta1_flowcollector.yaml, controllers/flowlogspipeline/flp_common_objects.go, controllers/flowlogspipeline/flp_test.go
Backport of https://github.com/netobserv/network-observability-operator/pull/351
=> [Backport] NETOBSERV-1050 & NETOBSERV-1065 Transport field in IPFIX exporter not working

controllers/flowlogspipeline/flp_common_objects.go, controllers/flowlogspipeline/flp_test.go, controllers/reconcilers/common.go
Two bug correction here:
Service annotations not being updated during reconcile, this had two effects:
- secret for TLS certificate were not being created resulting in pod failing to start
- the operator was  trying indefinitely to update the service
ServiceMonitor now adapt to the TLS configuration
=> NETOBSERV-1070: Fix reconcile from DISABLED to AUTO configuration

Makefile, controllers/ebpf/agent_controller.go, controllers/flowcollector_controller_test.go, controllers/reconcilers/namespaced_objects_manager.go, pkg/helper/client_helper.go, pkg/watchers/watcher.go, pkg/watchers/watcher_test.go
Backport of https://github.com/netobserv/network-observability-operator/pull/374
The problem was that copying certificates across namespaces was done on every reconciliation call, with or without digest change. This is not a critical issue as it would only trigger a no-op update, but it was screwing up our "updating" state detection.
There's actually two changes in this commit:
1. Fixing the "Updating" flag, so that it's not set when an update is actually performed (we need to fetch back the object (from cache) and check if the resource version was actually modified)
2. Fixing the certificate watching process to avoid unnecessary tries to update
Also:
- Add / fix tests
- Modify some logs to make important information more visible
- Makefile change for building manifest without error …
=> NETOBSERV-1076 Fix CR stuck in Updating state [1.3 backport]

api/v1beta1/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/manifests/bases/netobserv-operator.clusterserviceversion.yaml, docs/FlowCollector.md, docs/flowcollector-flows-netobserv-io-v1beta1.adoc, hack/asciidoc-gen.sh
- Generalize using backticks for cross-references of spec fields, enum values, etc.
- Format enum options as list when their description isn't too short
- A few rephrasing (e.g. in conversation tracking)
- should -> must
=> Doc updates:

.mk/development.mk
This kubectl call was ran everytime any make target was invoked, even something not requiring a cluster, resulting in errors or sometimes making any "make" call hanging (e.g. when kubectl points to an unreachable server / behind vpn)
=> (trivial) makefile: avoid kubectl calls in global scope

controllers/flowlogspipeline/metrics_definitions/node_egress_bytes_total.yaml, controllers/flowlogspipeline/metrics_definitions/node_ingress_bytes_total.yaml, controllers/flowlogspipeline/metrics_definitions/workload_egress_bytes_total.yaml, controllers/flowlogspipeline/metrics_definitions/workload_egress_packets_total.yaml, controllers/flowlogspipeline/metrics_definitions/workload_ingress_bytes_total.yaml, controllers/flowlogspipeline/metrics_definitions/workload_ingress_packets_total.yaml, go.mod, go.sum, vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/encode_prom.go, vendor/github.com/netobserv/flowlogs-pipeline/pkg/config/pipeline_builder.go, vendor/github.com/netobserv/flowlogs-pipeline/pkg/config/stage_params.go, vendor/modules.txt
Requires FLP PR: https://github.com/netobserv/flowlogs-pipeline/pull/448
Some observations when comparing byte rates from the plugin versus from prom metrics, e.g. between two nodes, e.g. with a promQL like that: 
```
sum(rate(netobserv_node_ingress_bytes_total{DstK8S_HostName="ip-10-0-137-27.eu-west-3.compute.internal"}[90s])) by (SrcK8S_HostName, DstK8S_HostName)
```
And on plugin's side, similarly, filtering on destination node name="ip-10-0-137-27.eu-west-3.compute.internal" , using Scope=Node and observing the top 5 flow rates in Overview:
Before this PR I see increased values, on prometheus side, in a range going from +20% to +80%
After this PR I still see increased values on prom side but seems much more reasonable, from +10% to +25% …
=> NETOBSERV-1131: Filter for Duplicate=false in metrics

controllers/ebpf/agent_controller.go
https://weaviate.io/blog/gomemlimit-a-game-changer-for-high-memory-applications
=> NETOBSERV-1107: Add GoMemLimit env setting to prevent ebpf agent OOM conditions

bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/descriptions/ocp.md, config/descriptions/upstream.md
This is a small update to the CSV description used for downstream, that we should probably have done already earlier: removes the mentions of our unofficial guides, replaced with a link to the official doc
=> Update downstream CSV description to link to official doc

.github/pull_request_template.md
PR template.
Here's how it looks like during creation:
Once it's created:
=> NETOBSERV-1222: Pull request template

api/v1alpha1/zz_generated.conversion.go, api/v1beta1/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/rbac/role.yaml, config/samples/flows_v1beta1_flowcollector.yaml, controllers/flowcollector_controller.go, controllers/flowcollector_controller_iso_test.go, controllers/flowlogspipeline/flp_common_objects.go, controllers/globals/globals.go, docs/FlowCollector.md
Added transform_filter to flp pipeline to add a clusterName field to flow logs.
clusterName is taken from config file. If blank, take clusterID from clusterVersion struct.
=> NETOBSERV-1182 added cluster name to flp configuration

api/v1beta1/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, docs/FlowCollector.md
The CRD doc displayed in the OLM console doesn't support italic text, so remove it from the doc (replaced with brackets)
n/a
=> NETOBSERV-1104: remove italic text in CRD doc

controllers/flowcollector_controller.go, controllers/flowcollector_controller_test.go, pkg/conditions/conditions.go
Improve CR status update:
- Fix `condition.Status` field. Only the active one should show `True`
- Fix Type field. It will now keep latests `Ready` / `Pending` / `Failed` messages with only one of these `True`
- Added messages
- Sorted conditions as oc command only show first item without checking `Status` field
[Screencast from 2023-08-23 11-15-55.webm](https://github.com/netobserv/network-observability-operator/assets/91894519/f12408a6-91fa-4762-ab2e-c6ae84ba38e1)
```
[julien@fedora network-observability-operator]$ oc get flowcollector
NAME      AGENT   SAMPLING (EBPF)   DEPLOYMENT MODEL   STATUS
cluster   EBPF    50                DIRECT             DeploymentInProgress
[julien@fedora network-observability-operator]$ oc get flowcollector
NAME      AGENT   SAMPLING (EBPF)   DEPLOYMENT …
```
=> NETOBSERV-1224 Flowcollector does not report status != Ready in OCP Console

api/v1beta1/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, docs/FlowCollector.md, docs/flowcollector-flows-netobserv-io-v1beta1.adoc, hack/asciidoc-gen.sh
=> Regenerate API reference asciidoc

controllers/constants/constants.go, controllers/flowcollector_objects.go, controllers/flowlogspipeline/flp_ingest_reconciler.go, controllers/flowlogspipeline/flp_monolith_reconciler.go, controllers/flowlogspipeline/flp_reconciler.go, controllers/flowlogspipeline/flp_transfo_reconciler.go, pkg/watchers/watcher.go
Add certificate copy to monitoring namespace.
n/a
=> NETOBSERV-1295: Fix cacert monitoring copy

controllers/constants/constants.go, controllers/flowcollector_objects.go, controllers/flowlogspipeline/flp_ingest_reconciler.go, controllers/flowlogspipeline/flp_monolith_reconciler.go, controllers/flowlogspipeline/flp_reconciler.go, controllers/flowlogspipeline/flp_transfo_reconciler.go, pkg/watchers/watcher.go
Backport of [NETOBSERV-1295](https://issues.redhat.com//browse/NETOBSERV-1295)
n/a
=> NETOBSERV-1295 backport: Fix certs monitoring copy 

controllers/ebpf/internal/permissions/permissions.go, controllers/flowcollector_controller.go, pkg/cleanup/cleanup.go, pkg/cleanup/cleanup_test.go, pkg/helper/flowcollector.go, pkg/test/kube_mock.go, pkg/watchers/watcher_test.go
Backport of https://github.com/netobserv/network-observability-operator/pull/427
=>  NETOBSERV-1314: cleanup old objects after upgrade [1.4 backport]

controllers/ebpf/internal/permissions/permissions.go, controllers/flowcollector_controller.go, pkg/cleanup/cleanup.go, pkg/cleanup/cleanup_test.go, pkg/helper/flowcollector.go, pkg/test/kube_mock.go, pkg/watchers/watcher_test.go
=> NETOBSERV-1314: cleanup old objects after upgrade

controllers/constants/constants.go, controllers/flowlogspipeline/flp_common_objects.go, controllers/flowlogspipeline/flp_test.go
Index duplicate field in Loki to improve query performance.
This is a very low cardinality field (2), and very used in queries, so it is an obvious improvement to do
- https://github.com/netobserv/network-observability-console-plugin/pull/380
=> NETOBSERV-314: NETOBSERV-1274 index type and duplicate (improve query perfs)

api/v1beta1/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, docs/FlowCollector.md, docs/flowcollector-flows-netobserv-io-v1beta1.adoc, hack/asciidoc-gen.sh
IPFIX exporter is now supported.
regen docs / bundle
n/a
=> Remove unsupported mention on IPFIX doc

bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/csv/bases/netobserv-operator.clusterserviceversion.yaml
The name says it all.  This adds the "Observability" category if it doesn't exist and adds Network Observability to this category.
=> NETOBSERV-1340: Add operator to "Observability" category in OperatorHub

controllers/flowlogspipeline/flp_common_objects.go, controllers/flowlogspipeline/flp_ingest_objects.go, controllers/flowlogspipeline/flp_ingest_reconciler.go, controllers/flowlogspipeline/flp_monolith_objects.go, controllers/flowlogspipeline/flp_monolith_reconciler.go, controllers/flowlogspipeline/flp_test.go, controllers/flowlogspipeline/flp_transfo_objects.go, controllers/flowlogspipeline/flp_transfo_reconciler.go, pkg/volumes/builder.go
This could cause the operator to crash if set to provided without provided structure
n/a
=> NETOBSERV-1346: Added checks to prevent dereferencing Provided cert nil pointer

pkg/helper/client_helper.go
Fix status oscillation by only counting Updated pods in pods count
n/a
=> NETOBSERV-1293: Fix status oscillation

.mk/development.mk, DEVELOPMENT.md, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/manager/manager.yaml, controllers/flowcollector_controller.go, main.go, pkg/watchers/watcher.go, pkg/watchers/watcher_test.go
=> NETOBSERV-754: add pprof, improve memory footprint

README.md, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/descriptions/ocp.md, config/descriptions/upstream.md
`1G` is no longer sufficient for zero-click Loki, we are looking to update it to `10G` in the PR below - as such we should update the relevant documentation as well
https://github.com/netobserv/documents/pull/57
=> Updated zero-click Loki references from 1G to 10G

pkg/watchers/watcher.go
CI tests are periodically failing due to a race condition - this should fix this issue
n/a
=> NETOBSERV-1354: fix concurrent access on watches

controllers/flowlogspipeline/metrics_definitions/namespace_egress_bytes_total.yaml, controllers/flowlogspipeline/metrics_definitions/namespace_egress_packets_total.yaml, controllers/flowlogspipeline/metrics_definitions/namespace_ingress_bytes_total.yaml, controllers/flowlogspipeline/metrics_definitions/namespace_ingress_packets_total.yaml, controllers/flowlogspipeline/metrics_definitions/node_egress_bytes_total.yaml, controllers/flowlogspipeline/metrics_definitions/node_egress_packets_total.yaml, controllers/flowlogspipeline/metrics_definitions/node_ingress_bytes_total.yaml, controllers/flowlogspipeline/metrics_definitions/node_ingress_packets_total.yaml, controllers/flowlogspipeline/metrics_definitions/workload_egress_bytes_total.yaml, controllers/flowlogspipeline/metrics_definitions/workload_egress_packets_total.yaml, controllers/flowlogspipeline/metrics_definitions/workload_ingress_bytes_total.yaml, controllers/flowlogspipeline/metrics_definitions/workload_ingress_packets_total.yaml
Backport of https://github.com/netobserv/network-observability-operator/pull/452
Previously, "inner" traffic (ie. traffic between pods running on the same node) wasn't included in the metrics
Requires https://github.com/netobserv/flowlogs-pipeline/pull/519
=> NETOBSERV-1344: include inner traffic in metrics [1.4 backport]

.github/workflows/push_image_pr.yml
Allow pre-merge bundles to point to release versions instead of main
=> Workflow: set release related img when relevant

.github/workflows/pull_request.yml, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml, config/manager/manager.yaml, go.mod
Disable http/2 in kube-rbac-proxy
n/a
=> NETOBSERV-1371: Disable http/2 in kube-rbac-proxy [1.4 backport]

controllers/ebpf/agent_controller.go, pkg/helper/flowcollector.go
to enable DNS we no longer have to run as privileged
https://github.com/netobserv/netobserv-ebpf-agent/pull/206
=> NETOBSERV-1245: NETOBSERV-1304: to enable DNS we no longer require privileged

bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml, config/manager/manager.yaml, controllers/consoleplugin/consoleplugin_objects.go, controllers/constants/constants.go, controllers/flowcollector_controller_test.go, controllers/flowlogspipeline/flp_common_objects.go, main.go
Additional remediations for CVE-2023-39325 CVE-2023-44487: Disable HTTP/2 on:
- Webhook server
- Metrics server
- FLP and Console plugin via env GODEBUG
- Update kube-rbac-proxy to v0.14.4
Also bump all k8s / contorller-runtime dependencies Stop support for go1.19, add support for go1.21 (still uses 1.20 for builds)
n/a
=> NETOBSERV-1369: Disable http/2

api/v1alpha1/flowcollector_webhook.go, api/v1beta1/flowcollector_webhook.go, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/samples/flows_v1beta2_flowcollector.yaml
This PR fix the empty loki querier url issue in conversion webhook
n/a
=> NETOBSERV-764: conversion fallback on ingester url

bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/samples/flows_v1beta2_flowcollector.yaml
=> Fix field wrongly named monolith/monolithic in sample CR

api/v1beta2/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, controllers/flowcollector_controller_iso_test.go, docs/FlowCollector.md, hack/cloned.flows.netobserv.io_flowcollectors.yaml
CRD doc fixes for loki manual params (explicit urls)
n/a
=> Fix loki manual params doc

controllers/consoleplugin/config/config.go, controllers/consoleplugin/config/static-frontend-config.yaml, controllers/consoleplugin/consoleplugin_objects.go, controllers/consoleplugin/consoleplugin_reconciler.go, controllers/consoleplugin/consoleplugin_test.go, controllers/ebpf/agent_controller.go, controllers/ebpf/internal/permissions/permissions.go, controllers/flowcollector_controller_console_test.go, controllers/flowlogspipeline/flp_ingest_reconciler.go, controllers/flowlogspipeline/flp_monolith_reconciler.go, controllers/flowlogspipeline/flp_transfo_reconciler.go, controllers/reconcilers/common.go, pkg/helper/client_helper.go
- import static config for frontend config containing `columns` and `filters` definitions.
- move console plugin args related to `server` and `loki` to configmap for consistency
It also allow devs/users to remove the `ownerReferences` metadata of any resource created by FlowCollector to skip update on these.
The controller will log the following every reconcile loop:
```
2023-10-25T16:12:22.874Z INFO SKIP *v1.ConfigMap update since not owned {"controller": "flowcollector", "controllerGroup": "flows.netobserv.io", "controllerKind": "FlowCollector", "FlowCollector": {"name":"cluster"}, "namespace": "", "name": "cluster", "reconcileID": "41a05182-d7ba-4aeb-8a84-c03e3cdd80c2", "Namespace": "netobserv", "Name": "console-plugin-config"}
```
To quick reload the configmap, you need to restart the …
=> NETOBSERV-1150 Console plugin columns & filters as config

controllers/consoleplugin/config/static-frontend-config.yaml
- remove duplicate DSCP field
- fix fields :
- DNSLatency 
- Duration
- Collection time
- Collection latency
- ICMP removed from default
- fix ICMP code filter
https://github.com/netobserv/network-observability-console-plugin/pull/427/files
=> NETOBSERV-1400 Feature filters are observed even though they are not enabled

controllers/flowlogspipeline/flp_common_objects.go, controllers/flowlogspipeline/flp_ingest_objects.go, controllers/flowlogspipeline/flp_monolith_objects.go, controllers/flowlogspipeline/flp_monolith_reconciler.go, controllers/flowlogspipeline/flp_pipeline_builder.go, controllers/flowlogspipeline/flp_test.go, controllers/flowlogspipeline/flp_transfo_objects.go, controllers/flowlogspipeline/flp_transfo_reconciler.go
Make it easier to build a FLP pipeline outside of the FLP reconciler. This will be useful for [NETOBSERV-627](https://issues.redhat.com//browse/NETOBSERV-627)
- Create a new file flp_pipeline_builder.go that contains the pipeline building code, extracted from flp_common_objects.go
- Make some of these functions exported, for external usage
- Some API enhancements such as builder.NewGRPCPipeline for consumer friendlyness
n/a
=> Refactor FLP builder

api/v1alpha1/flowcollector_webhook.go, api/v1alpha1/zz_generated.conversion.go, api/v1beta1/flowcollector_types.go, api/v1beta1/zz_generated.conversion.go, api/v1beta1/zz_generated.deepcopy.go, api/v1beta2/flowcollector_types.go, api/v1beta2/zz_generated.deepcopy.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, controllers/flowcollector_controller_iso_test.go, controllers/flowlogspipeline/flp_pipeline_builder.go, docs/FlowCollector.md, hack/cloned.flows.netobserv.io_flowcollectors.yaml
- ensure cluster id is Loki label
- don't append it if not in multicluster environment
n/a
=> NETOBSERV-1217: Added flag to enable multiCluster configuration

api/v1alpha1/flowcollector_webhook.go, api/v1beta1/flowcollector_webhook.go, controllers/consoleplugin/consoleplugin_test.go, controllers/flowcollector_controller.go, controllers/flowlogspipeline/flp_test.go, pkg/helper/loki_config.go
Host like "loki-gateway-http.svc" seem invalid
n/a
=> NETOBSERV-1398: fix loki url when same namespace

api/v1beta2/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, docs/FlowCollector.md, hack/cloned.flows.netobserv.io_flowcollectors.yaml
Remove RTT unsupported mentions.
n/a
=> NETOBSERV-1406 Remove RTT unsupported mentions

controllers/consoleplugin/config/config.go, controllers/consoleplugin/config/static-frontend-config.yaml
Fix missing drops information in table view
FYI there is also https://github.com/netobserv/network-observability-console-plugin/pull/437 opened on `pktDrop` filters
https://github.com/netobserv/network-observability-console-plugin/pull/440
=> NETOBSERV-1432 Missing drops information in table view

api/v1alpha1/flowcollector_types.go, api/v1alpha1/flowcollector_webhook.go, api/v1alpha1/zz_generated.conversion.go, api/v1beta1/flowcollector_types.go, api/v1beta1/flowcollector_webhook.go, api/v1beta1/flowcollector_webhook_test.go, api/v1beta1/zz_generated.conversion.go, api/v1beta2/flowcollector_types.go, api/v1beta2/zz_generated.deepcopy.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/samples/flows_v1beta2_flowcollector.yaml, controllers/ebpf/agent_controller.go, controllers/flowcollector_controller_certificates_test.go, controllers/flowcollector_controller_ebpf_test.go, controllers/flowcollector_controller_iso_test.go, controllers/flp/flp_common_objects.go, docs/FlowCollector.md, hack/cloned.flows.netobserv.io_flowcollectors.yaml, pkg/conversion/conversion.go, pkg/conversion/conversion_test.go
This PR updates enums to pascal case. It replaces https://github.com/netobserv/network-observability-operator/pull/483 which is outdated.
n/a
=> NETOBSERV: 1374 Make enums pascal case

controllers/ebpf/agent_controller.go, controllers/flowcollector_controller_certificates_test.go
The agent IP as detected by the agent itself could potentially differ from the expected machine network IP, e.g. getting " 192.168.12.2" instead of "10.10.10.2".
By forcing the IP from the operator by inferring its host node IP, we ensure using the correct one
Note that the AGENT_IP env was already implemented on Agent side to override IP detection
n/a
=> NETOBSERV-1430: make operator provide agent IP

controllers/consoleplugin/config/config.go, controllers/consoleplugin/config/static-frontend-config.yaml, controllers/consoleplugin/consoleplugin_objects.go, controllers/ebpf/agent_controller.go
=> NETOBSERV-1298: Add netobserv operator changes to support dup list

config/samples/flowmetrics/pods_incoming_bytes.yaml, config/samples/flowmetrics/pods_outgoing_bytes.yaml, config/samples/flowmetrics/services_incoming_bytes.yaml
Provide sample FlowMetrics files to get top pods/services bandwidth The metrics can be queried with:
- Pods incoming: `topk(10, sum(rate(netobserv_pod_incoming_bytes_total[1m])) by (DstK8S_Name, DstK8S_Namespace))`
- Pods outgoing: `topk(10, sum(rate(netobserv_pod_outgoing_bytes_total[1m])) by (SrcK8S_Name, SrcK8S_Namespace))`
- Services incoming: `topk(10, sum(rate(netobserv_service_incoming_bytes_total[1m])) by (DstK8S_Name, DstK8S_Namespace))`
n/a
=> NETOBSERV-1017: pods/services bandwidth (flowmetrics / dev preview)

controllers/consoleplugin/consoleplugin_objects.go, controllers/consoleplugin/consoleplugin_test.go, controllers/constants/constants.go, controllers/flowcollector_controller_certificates_test.go, controllers/flp/flp_pipeline_builder.go, controllers/flp/flp_test.go, pkg/loki/labels.go
This PR removes `FlowDirection` and `Duplicate` labels when deduper merge mode is enabled.
It also centralize labels array in a single function (`K8S_ClusterName` was not sent to console plugin).
n/a
=> NETOBSERV-1407 - Loki labels for deduper merge

Makefile, apis/flowcollector/v1beta1/flowcollector_types.go, apis/flowcollector/v1beta2/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/csv/bases/netobserv-operator.clusterserviceversion.yaml, docs/FlowCollector.md, hack/cloned.flows.netobserv.io_flowcollectors.yaml, hack/crd2csvSpecDesc.sh
Added to CSV:
This is [made using a complex mechanism](https://github.com/openshift/console/blob/d2fbe0a4ddaa6dca4f93d4c0c521943ceb277e19/frontend/packages/console-shared/src/components/dynamic-form/utils.ts#L91-L109) relying on required fields / dependencies between fields and falling back on the number of subfields. I would suggest to keep it as is.
see [related discussion](https://redhat-internal.slack.com/archives/C6A3NV5J9/p1695139049459949?thread_ts=1695116635.617689&cid=C6A3NV5J9) and https://github.com/openshift/console/pull/13181
These will make the CSV harder to maintain but the UX is way better in the console.
---
---
---
https://github.com/netobserv/network-observability-operator/pull/329 
https://github.com/netobserv/network-observability-operator/pull/467 …
=> NETOBSERV-791 Better organize OLM form

.mk/development.mk, hack/swap-image-csv.sh
Updating `swap-image-csv.sh` script such that DOWNSTREAM_DEPLOYMENT env variable could be patched in CSV and minor fixes to set-plugin-image.
n/a
=> swap-image-csv.sh updates and minor fixes to set-plugin-image

bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/manager/manager.yaml, controllers/consoleplugin/consoleplugin_objects.go, controllers/ebpf/agent_controller.go, controllers/flp/flp_common_objects.go, pkg/helper/security.go
- Use by default this security context, for all workloads except eBPF Agent:
```yaml
securityContext:
allowPrivilegeEscalation: false
capabilities:
drop:
- ALL
readOnlyRootFilesystem: true
```
- On agent, if not privileged, use a slightly modified version, with necessary caps added
n/a
=> NETOBSERV-1308: security context enforcement

apis/flowcollector/v1alpha1/flowcollector_webhook.go, apis/flowcollector/v1alpha1/zz_generated.conversion.go, apis/flowcollector/v1beta1/flowcollector_webhook.go, apis/flowcollector/v1beta1/zz_generated.conversion.go, apis/flowcollector/v1beta2/flowcollector_types.go, apis/flowcollector/v1beta2/zz_generated.deepcopy.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/samples/flows_v1beta2_flowcollector.yaml, controllers/consoleplugin/config/static-frontend-config.yaml, controllers/flowcollector_controller_iso_test.go, controllers/flp/flp_pipeline_builder.go, docs/FlowCollector.md, go.mod, go.sum, hack/cloned.flows.netobserv.io_flowcollectors.yaml, hack/crd2csvSpecDesc.sh, vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/transform_network.go, vendor/modules.txt
Add a field in flowcollector to enable zones in flows
https://github.com/netobserv/flowlogs-pipeline/pull/575
=> NETOBSERV-1203 Add field to enable zone

.mk/development.mk
=> bug fix to use OPERATOR_NS instead

apis/flowcollector/v1beta1/flowcollector_types.go, apis/flowcollector/v1beta1/flowcollector_webhook.go, apis/flowcollector/v1beta1/zz_generated.conversion.go, apis/flowcollector/v1beta1/zz_generated.deepcopy.go, apis/flowcollector/v1beta2/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/csv/bases/netobserv-operator.clusterserviceversion.yaml, controllers/ebpf/agent_controller.go, controllers/flp/flp_pipeline_builder.go, docs/FlowCollector.md, hack/cloned.flows.netobserv.io_flowcollectors.yaml, pkg/helper/flowcollector.go, pkg/loki/labels.go
supersedes https://github.com/netobserv/network-observability-operator/pull/540
- Add "AddZone" field also in v1beta1
- Update descriptions / avoid using "will"
- Use helper functions (centralizes handling of default/nil case)
n/a
=> NETOBSERV-1203: minor adjustments

apis/flowcollector/v1beta1/flowcollector_types.go, apis/flowcollector/v1beta1/flowcollector_webhook.go, apis/flowcollector/v1beta1/zz_generated.conversion.go, apis/flowcollector/v1beta1/zz_generated.deepcopy.go, apis/flowcollector/v1beta2/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/csv/bases/netobserv-operator.clusterserviceversion.yaml, controllers/ebpf/agent_controller.go, controllers/flp/flp_pipeline_builder.go, docs/FlowCollector.md, hack/cloned.flows.netobserv.io_flowcollectors.yaml, pkg/helper/flowcollector.go, pkg/loki/labels.go
Backport of https://github.com/netobserv/network-observability-operator/pull/545
- Add "AddZone" field also in v1beta1
- Update descriptions / avoid using "will"
- Use helper functions (centralizes handling of default/nil case)
n/a
=> NETOBSERV-1203: minor adjustments [backport 1.5]

controllers/flowcollector_controller.go, controllers/flowcollector_controller_certificates_test.go, controllers/flp/flp_controller.go, controllers/monitoring/monitoring_controller.go, pkg/manager/status/util.go
- Add more info on test failure during certificate test cleanup
- Fix an error occuring when deleting the CR: controllers would still try to update the CR status despite the CR being deleted
=> Try fixing flaky test

controllers/constants/constants.go, controllers/flp/flp_test.go
This is drastically reducing the number of streams while keeping query performances almost identical
cf details in https://github.com/netobserv/network-observability-operator/pull/554#issuecomment-1921041243
to be backported in 1.5
=> NETOBSERV-1458: reduce loki streams, index FlowInfra

image-references, manifests/image-references
[NETOBSERV-1467](https://issues.redhat.com//browse/NETOBSERV-1467) - [it appears](https://docs.ci.openshift.org/docs/how-tos/onboarding-a-new-component/#product-builds-and-becoming-part-of-an-openshift-release) we need this file to pass operand images to  be able to build pre-merge images 
See this WIP PR: https://github.com/openshift/release/pull/48224, the [e2e-test failed](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/48224/rehearse-48224-pull-ci-netobserv-network-observability-operator-main-e2e-operator/1752728559681540096) with error when trying to have flowlogs-pipeline as input.
```
* could not resolve inputs: could not determine inputs for step [input:flowlogs-pipeline]: could not resolve base image from ocp/latest:flowlogs-pipeline: …
```
=> image references file

controllers/flowcollector_controller_certificates_test.go, controllers/flowcollector_controller_console_test.go, controllers/flowcollector_controller_iso_test.go, controllers/flowcollector_controller_minimal_test.go, controllers/flowcollector_controller_test.go, controllers/flp/flp_controller_flowmetrics_test.go, controllers/flp/flp_controller_test.go, controllers/flp/suite_test.go, controllers/monitoring/monitoring_controller_test.go, controllers/monitoring/suite_test.go, controllers/suite_test.go, pkg/manager/status/status_manager.go, pkg/test/envtest.go
Backport of  https://github.com/netobserv/network-observability-operator/pull/557
There was is timing issue with FlowCollector taking more time than the test timeout to be deleted. One option could have been to increase the timeout, but here we're simply checking that the DeletionTimestamp field is set, which means the resource has been marked for deletion.
Another issue found while testing, was the eBPF agent potentially calling `status.CheckDaemonSetProgress` with a nil parameter, which triggered an error. Adding nil-checks to StatusManager functions.
n/a
=> Fix envtests with FlowCollector deletion [1.5 backport]

README.md, apis/flowcollector/v1alpha1/flowcollector_types.go, apis/flowcollector/v1beta1/flowcollector_types.go, apis/flowcollector/v1beta2/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/samples/flows_v1beta1_flowcollector.yaml, config/samples/flows_v1beta2_flowcollector.yaml, docs/FlowCollector.md, hack/cloned.flows.netobserv.io_flowcollectors.yaml
As shown [here](https://docs.google.com/spreadsheets/d/1qakBaK1dk_rERO30k1cSR4W-Nn0SXW4A3lqQ1sZC4rE/edit#gid=1155551118) in run11, this tuning drastically reduces memory used due to kafka batching, retrieving similar level than in 1.4 (even slightly better).
It should be verified on large-scale perf tests
=> NETOBSERV-1470: Reduce memory usage in agent due to kafka batches

README.md, apis/flowcollector/v1alpha1/flowcollector_types.go, apis/flowcollector/v1beta1/flowcollector_types.go, apis/flowcollector/v1beta2/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/samples/flows_v1beta1_flowcollector.yaml, config/samples/flows_v1beta2_flowcollector.yaml, docs/FlowCollector.md, hack/cloned.flows.netobserv.io_flowcollectors.yaml
Backport of https://github.com/netobserv/network-observability-operator/pull/567
As shown [here](https://docs.google.com/spreadsheets/d/1qakBaK1dk_rERO30k1cSR4W-Nn0SXW4A3lqQ1sZC4rE/edit#gid=1155551118) in run11, this tuning drastically reduces memory used due to kafka batching, retrieving similar level than in 1.4 (even slightly better).
It should be verified on large-scale perf tests
=> NETOBSERV-1470: reduce memory usage in agent due to kafka batches [1.5 backport]

controllers/consoleplugin/config/static-frontend-config.yaml, controllers/constants/constants.go, controllers/flp/flp_pipeline_builder.go, controllers/flp/flp_test.go, pkg/loki/labels.go
- ~Rename `FlowDirection` to `NodeDirection`,~ improved descriptions and restore `FlowDirection` label when using deduper merge
- Skip reinterpret field renaming since it's now done directly in eBPF
- Update console plugin fields / queries to plural
To setup deduper merge, simply add the following config in ebpf debug (or advanced) configuration:
```yaml
advanced:
env:
DEDUPER_JUST_MARK: "false"
DEDUPER_MERGE: "true"
```
https://github.com/netobserv/netobserv-ebpf-agent/pull/275
https://github.com/netobserv/flowlogs-pipeline/pull/601
https://github.com/netobserv/network-observability-console-plugin/pull/482
A followup to remove Duplicate field is available at: https://github.com/netobserv/network-observability-operator/pull/580
If you are not familiar with our processes or don't know what …
=> NETOBSERV-1466 NodeDirection / IfDirection

controllers/consoleplugin/consoleplugin_test.go, controllers/ebpf/agent_controller.go
=> NETOBSERV-1474: change dup mode to use list as the default

controllers/flowcollector_controller.go
Since removing ipfix, we don't use finalizers anymore. However users upgrading from a 1.5 will still have one set in their CR. So we need, for a release, to continue checking for the finalizer, and remove it if found.
n/a
=> NETOBSERV-1568: reintroduce finalizer check to remove any remaining finalizer

apis/flowcollector/v1beta1/flowcollector_types.go, apis/flowcollector/v1beta2/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/openshift/namespace.yaml, controllers/ebpf/agent-metrics-test.go, controllers/ebpf/agent-metrics.go, controllers/ebpf/agent_controller.go, controllers/ebpf/internal/permissions/permissions.go, controllers/flowcollector_controller.go, controllers/flp/flp_common_objects.go, controllers/flp/flp_controller.go, controllers/reconcilers/common.go, docs/FlowCollector.md, pkg/helper/monitoring.go
add TLS config support to ebpf agent
https://github.com/netobserv/netobserv-ebpf-agent/pull/305
https://github.com/netobserv/network-observability-operator/pull/604
=> NETOBSERV-1532: add TLS support to ebpf agent metrics config

controllers/ebpf/agent_controller.go
Check sampling > 0 instead of 1 such that the SAMPLING env var is set for eBPF pods and therefore seen on eBPF metric dashboard. It shows sampling 0 even if its set to 1 which might be misleading
n/a
=> Sampling check

pkg/dashboards/health.go
add flow filter to ebpf agent health dashboard
https://github.com/netobserv/netobserv-ebpf-agent/pull/316
=> NETOBSERV-1605: add flow filter to ebpf agent dashboard

controllers/flp/flp_common_objects.go, controllers/flp/flp_controller_flowmetrics_test.go, controllers/flp/flp_monolith_objects.go, controllers/flp/flp_monolith_reconciler.go, controllers/flp/flp_test.go, controllers/flp/flp_transfo_objects.go, controllers/flp/flp_transfo_reconciler.go, controllers/flp/metrics_api_test.go, go.mod, go.sum, pkg/volumes/builder.go, vendor/github.com/netobserv/flowlogs-pipeline/pkg/config/config.go, vendor/github.com/netobserv/flowlogs-pipeline/pkg/config/pipeline_builder.go, vendor/github.com/netobserv/flowlogs-pipeline/pkg/utils/kubernetes.go, vendor/golang.org/x/net/http/httpproxy/proxy.go, vendor/golang.org/x/net/http2/frame.go, vendor/golang.org/x/net/http2/pipe.go, vendor/golang.org/x/net/http2/server.go, vendor/golang.org/x/net/http2/testsync.go, vendor/golang.org/x/net/http2/transport.go, vendor/modules.txt
Added support to FLP dynamic configmap
[FLP PR](https://github.com/netobserv/flowlogs-pipeline/pull/607)
=> NETOBSERV-1427 Added support to FLP dynamic configmap

controllers/flp/flp_transfo_objects.go
```shell
time=2024-04-30T15:31:14Z level=error msg=Cannot get dynamic config: configmaps "flowlogs-pipeline-transformer-config-dynamic" is forbidden: User "system:serviceaccount:netobserv:flowlogs-pipeline-transformer" cannot get resource "configmaps" in API group "" in the namespace "netobserv"
```
n/a
=> NETOBSERV-1626: add configmaps to service account

Makefile
It more efficient than current default which client-side which embed the last applied state in metadata and as the object increase its possible to exceed APIs max object size
for more detial refer to
https://kubernetes.io/docs/reference/using-api/server-side-apply/#comparison-with-client-side-apply
n/a
=> NETOBSERV-1613: switch kubectl apply to use server-side

apis/flowmetrics/v1alpha1/flowmetric_types.go, bundle/manifests/flows.netobserv.io_flowmetrics.yaml, config/crd/bases/flows.netobserv.io_flowmetrics.yaml, docs/FlowMetric.md
=> NETOBSERV-1632: metrics API, allow empty unit

apis/flowcollector/v1beta1/flowcollector_types.go, apis/flowcollector/v1beta2/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, controllers/ebpf/agent-metrics.go, docs/FlowCollector.md
=> NETOBSERV-1625: (follow-up) mention other possible cause for ebpf drops

apis/flowcollector/v1beta1/flowcollector_types.go, apis/flowcollector/v1beta2/flowcollector_types.go
use consistent string for ebpf drop flow alert
n/a
=> use the same string for flowdrop alert to disable alert if needed

apis/flowcollector/v1beta1/flowcollector_types.go, apis/flowcollector/v1beta2/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/samples/flows_v1beta2_flowcollector.yaml, docs/FlowCollector.md, pkg/helper/flowcollector.go
enable ebpf metrics by default while still keeping the config in case we need to disable it
n/a
=> enable ebpf metrics by default while keep the knob in case we need to disable

controllers/flp/flp_controller.go, controllers/flp/flp_monolith_reconciler.go, controllers/flp/flp_transfo_reconciler.go
=> NETOBSERV-1647: do not get Loki certificates when Loki is disabled

bundle/manifests/flows.netobserv.io_flowcollectors.yaml, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/crd/patches/webhook_in_flowcollectors.yaml
Note we're talking here about versions of ConversionReview (ie. apiextension), NOT versions of our CRDs
- Use same versions for flowcollector and flowmetrics
- Use just v1 as the only other (v1beta1) was dropped a while ago (kube 1.22 / 2021)
=> NETOBSERV-1665: use v1 for conversionReviewVersions

controllers/consoleplugin/consoleplugin_objects.go, controllers/consoleplugin/consoleplugin_reconciler.go, controllers/constants/constants.go, controllers/flowcollector_controller.go, pkg/helper/flowcollector.go
To be used with a standalone plugin build image such as: `quay.io/jotak/network-observability-standalone-frontend:riviera2024`
Set `spec.consolePlugin.advanced.env.TEST_CONSOLE` `"true"`
n/a
=> H&H: Allow using Test Console (standalone) from operator 🤘

controllers/consoleplugin/consoleplugin_objects.go, pkg/dashboards/dashboard_test.go, pkg/metrics/predefined_metrics.go, pkg/metrics/predefined_metrics_test.go
Add cluster & zone to predefined metrics
They're only added when those features are enabled.
n/a
=> NETOBSERV-1672: add cluster & zone to predefined metrics

controllers/consoleplugin/consoleplugin_objects.go, pkg/dashboards/dashboard_test.go, pkg/metrics/predefined_metrics.go, pkg/metrics/predefined_metrics_test.go
cf https://github.com/netobserv/network-observability-operator/pull/665
=> NETOBSERV-1672: add cluster & zone to predefined metrics (#665) [1.6 backport]

controllers/consoleplugin/consoleplugin_objects.go, controllers/consoleplugin/consoleplugin_reconciler.go, controllers/consoleplugin/consoleplugin_test.go
=> NETOBSERV-1647: Do not load loki cert when loki disabled

bundle/manifests/flows.netobserv.io_flowcollectors.yaml, config/crd/patches/webhook_in_flowcollectors.yaml, controllers/consoleplugin/consoleplugin_objects.go, controllers/consoleplugin/consoleplugin_reconciler.go
cf https://github.com/netobserv/network-observability-operator/pull/669
also includes backport of https://github.com/netobserv/network-observability-operator/pull/662 to fix flaky CI
=> NETOBSERV-1647: Do not load loki cert when loki disabled [Backport 1.6]

Makefile
with `kubectl apply --server-side`, sometimes we get conflict errors, such as after using the make target `set-xxx-image` which amends the deployment env variables. Using `--force-conflicts` allows to ignore such conflict, and makes the new deployment prevail.
=> force conflicts on deploy

bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/csv/bases/netobserv-operator.clusterserviceversion.yaml
Same with subnet labels / openshift auto-detect ([NETOBSERV-1734](https://issues.redhat.com//browse/NETOBSERV-1734))
This is to avoid confusion, since nillable bools are not managed properly in OLM forms They can be access from YAML
A longer-term solution will be to replace all our nillable bools with enums in a next API version
n/a
=> NETOBSERV-1731: hide metrics enable setting from form

pkg/metrics/predefined_metrics.go
Add more metrics info to make prometheus datasource suiting for replacing loki datasource in overview page
- Add drop cause & TCP state labels to the drop metrics
- When only prometheus is enabled, turn on "workload_ingress_packets_total" by default
n/a
=> NETOBSERV-1649: add drop cause & state labels to metrics

bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/csv/bases/netobserv-operator.clusterserviceversion.yaml, controllers/consoleplugin/consoleplugin_objects.go, controllers/flp/flp_pipeline_builder.go, controllers/flp/flp_test.go, pkg/dashboards/dashboard_test.go, pkg/metrics/predefined_metrics.go, pkg/metrics/predefined_metrics_test.go, pkg/test/util/utils.go
Backporting:
- [NETOBSERV-1649](https://issues.redhat.com//browse/NETOBSERV-1649)
- [NETOBSERV-1731](https://issues.redhat.com//browse/NETOBSERV-1731)
- [NETOBSERV-1705](https://issues.redhat.com//browse/NETOBSERV-1705)
- [NETOBSERV-1734](https://issues.redhat.com//browse/NETOBSERV-1734)
=> Prepare 1.6.1

controllers/monitoring/monitoring_controller.go, controllers/monitoring/monitoring_objects.go, pkg/dashboards/dashboard_test.go, pkg/dashboards/health.go
Switch to using "workload_flows_total" when needed
n/a
=> NETOBSERV-1746: Adapt health dashboard to flows metrics enabled

apis/flowcollector/v1beta1/flowcollector_types.go, apis/flowcollector/v1beta1/zz_generated.conversion.go, apis/flowcollector/v1beta2/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/samples/flows_v1beta2_flowcollector.yaml, controllers/consoleplugin/config/static-frontend-config.yaml, controllers/ebpf/agent_controller.go, docs/FlowCollector.md
using flow filter with TCP flags we can detect TCP syn flood
also extend console plugin filter and column to suppirt TCP flags field
https://github.com/netobserv/netobserv-ebpf-agent/pull/367
=> NETOBSERV-1755 Add filter for TCP flags

controllers/ebpf/agent_controller.go
Users can configure DNS tracking port as an env var in case we need to use none default port `53`
Example:
```yaml
spec:
agent:
ebpf:
advanced:
env:
DNS_TRACKING_PORT : "5353"
```
n/a
=> NETOBSERV-1777: Allow DNS tracking to use configurable port for tracking

controllers/monitoring/monitoring_controller.go, pkg/test/envtest.go, vendor/github.com/openshift/api/security/v1/zz_generated.crd-manifests/0000_03_config-operator_01_securitycontextconstraints.crd.yaml, vendor/github.com/openshift/api/security/v1/zz_generated.crd-manifests/doc.go, vendor/modules.txt
There was a wrong assumption that if ServiceMonitor api is installed then it's openshift. ServiceMonitor is an API from upstream prometheus. Fix it so openshift dashboards are only installed when running on openshift.
Add openshift security v1 API to envtests as this is used to detect openshift.
n/a
=> NETOBSERV-1758: fix error with monitoring ctrl w/o openshift

Makefile, catalog.Dockerfile, catalog/index.yaml, hack/update_fbc.sh
This catalog will replace the catalog we currently use, for now, we have Makefile target for both.
n/a
=>  NETOBSERV-1786: Add support to build file based catalog

.mk/development.mk, FAQ.md
- Remove the requirement to build our own image (requires https://github.com/netobserv/network-observability-console-plugin/pull/576)
- Rewrite FAQ entry
- Add make target (make use-test-console)
Fixes #124
=> Test console improvements

apis/flowcollector/v1beta1/flowcollector_types.go, apis/flowcollector/v1beta2/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, controllers/ebpf/agent_controller.go, docs/FlowCollector.md
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
(cherry picked from commit 38031f1830161b98affc29534fb95b5b6286ef3e)
n/a
=> Allow flow filtering for L4 protocols using two ports [BP to 1.6.2]

controllers/consoleplugin/config/config.go, controllers/consoleplugin/consoleplugin_objects.go, controllers/flp/flp_common_objects.go, controllers/flp/flp_pipeline_builder.go
- Append `namespace` using `metricRelabelConfigs` in prometheus metrics
- Add `devUrl` to console config
/!\ this doesn't work with user workload monitoring, you need to enable cluster monitoring
```
make set-release-kind-downstream
```
User need to have permission to `metrics.k8s.io/pods`. Example for user `test` in `netobserv` namespace:
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
name: metrics
namespace: netobserv
rules:
- verbs:
- create
apiGroups:
- metrics.k8s.io
resources:
- pods
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
name: metrics
namespace: netobserv
subjects:
- kind: User
apiGroup: rbac.authorization.k8s.io
name: test
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: Role
name: metrics
```
n/a
If you are not familiar with …
=> NETOBSERV-1689 Allow multi-tenant Prometheus queries

controllers/ebpf/agent_controller.go
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
(cherry picked from commit 192b5b9ba2fc8df099f4cafeae839661d6904580)
n/a
=> NETOBSERV-1777: Allow DNS tracking to use configurable port for tracking [BP]

apis/flowcollector/v1beta1/flowcollector_types.go, apis/flowcollector/v1beta2/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/samples/flows_v1beta2_flowcollector.yaml, controllers/consoleplugin/config/static-frontend-config.yaml, controllers/consoleplugin/consoleplugin_objects.go, controllers/ebpf/agent_controller.go, controllers/flp/flp_pipeline_builder.go, docs/FlowCollector.md, pkg/helper/flowcollector.go
changes to support ovs monitoring config and console bits
FC config to enable ovs monitoring fearure
```yaml
agent:
type: eBPF
ebpf:   
privileged: true
features:
- "OvsMonitor"
```
https://github.com/netobserv/netobserv-ebpf-agent/pull/286
=> NETOBSERV-1642: Ovs monitoring feature

controllers/ebpf/agent_controller.go
Allow port filtering if protocol not set
n/a
=> NETOBSERV-1779 allow port filtering if protocol not set

apis/flowcollector/v1beta1/flowcollector_types.go, apis/flowcollector/v1beta2/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, controllers/ebpf/agent_controller.go, docs/FlowCollector.md
Allow filtering TCP/UDP/SCTP using two ports syntax like "90,100" to filter either on port 90 or 100
https://github.com/netobserv/netobserv-ebpf-agent/pull/389
=> NETOBSERV-1803: Allow flow filtering for L4 protocols using two ports

pkg/discover/apis.go
As pinpointed in https://github.com/netobserv/network-observability-operator/pull/756, the current discovery mechanism ignores the resource versions hence it might advertize an API as being available despite it being an old removed one.
This patch adds version check to the discovery mechanism. If an API is found using a removed version, it will be considered as not available.
=> Check version when discovering api

Dockerfile, Makefile
@OlivierCazade do you know what we need to check to make sure this won't break anything?
=> Fix podman builds

bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/constants/constants.go, controllers/flp/flp_controller.go, controllers/flp/flp_controller_test.go, controllers/flp/flp_monolith_reconciler.go, controllers/flp/flp_test.go, controllers/flp/flp_transfo_reconciler.go, pkg/loki/roles.go, pkg/manager/manager.go, pkg/resources/static_resources.go
A new role is created for reading metrics. This role is separate from netobserv-reader role, because it is meant to be namespace-scoped and not cluster-wide (whereas for Loki multi-tenancy, netobserv-reader has to be bound cluster-wide).
To use this role, just write: 
```bash
oc adm policy add-role-to-user netobserv-metrics-reader test -n my-namespace
```
This will grant user "test" access to the netflow metrics in the "my-namespace" namespace, which can be used both in the developer view and in the adminitrator view.
n/a
=> NETOBSERV-1856: new role for metrics reading permissions

.tekton/network-observability-operator-bundle-pull-request.yaml, .tekton/network-observability-operator-bundle-push.yaml, .tekton/network-observability-operator-fbc-pull-request.yaml, .tekton/network-observability-operator-fbc-push.yaml, catalog/index.yaml, hack/bundle_digest.sh, hack/patch_catalog.py, hack/update-build.sh
Automatically update bundle reference in the catalog using nudge feature from konflux
n/a
=> NETOBSERV-1786: Automatically update bundle reference in the catalog

apis/flowcollector/v1beta2/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, controllers/flp/flp_controller_flowmetrics_test.go, controllers/flp/flp_test.go, controllers/flp/metrics_api_test.go, docs/FlowCollector.md, pkg/dashboards/dashboard_test.go, pkg/metrics/predefined_metrics.go
Add egress metrics to prom defaults
n/a
=> NETOBSERV-1848 Enable egress metric to show more traffic

apis/flowmetrics/v1alpha1/flowmetric_types.go, apis/flowmetrics/v1alpha1/flowmetric_webhook.go, apis/flowmetrics/v1alpha1/zz_generated.deepcopy.go, bundle/manifests/flows.netobserv.io_flowmetrics.yaml, config/crd/bases/flows.netobserv.io_flowmetrics.yaml, config/samples/flowmetrics/dns_requests.yaml, config/samples/flowmetrics/dns_responses.yaml, controllers/consoleplugin/config/config.go, controllers/consoleplugin/consoleplugin_objects.go, controllers/consoleplugin/consoleplugin_test.go, controllers/flp/flp_pipeline_builder.go, docs/FlowMetric.md, go.mod, go.sum, pkg/helper/cardinality.go, pkg/helper/helpers.go, vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/encode_prom.go, vendor/github.com/prometheus/common/config/http_config.go, vendor/golang.org/x/oauth2/LICENSE, vendor/modules.txt
- Add "remap" to FlowMetrics CRD
- Add examples with DNS requests/responses
- Some variables renamed for more clarity
FLP: https://github.com/netobserv/flowlogs-pipeline/pull/698
=> NETOBSERV-1772: allow prom label remapping

controllers/monitoring/monitoring_controller.go, pkg/helper/client_helper.go, pkg/helper/flowcollector.go
Set namespace ownership using a new `netobserv-managed: true` label so users can bypass reconcile loop if they want to customize labels by setting it to false.
The `ownerReference` is not set to namespace object to avoid unexpected deletions.
n/a
=> NETOBSERV-1811 set namespace ownership

.tekton/network-observability-operator-bundle-pull-request.yaml, .tekton/network-observability-operator-bundle-push.yaml, .tekton/network-observability-operator-fbc-pull-request.yaml, .tekton/network-observability-operator-fbc-push.yaml, .tekton/network-observability-operator-pull-request.yaml, .tekton/network-observability-operator-push.yaml
Enable prefetch dependencies in konlfux build pipelines, this is not needed to build but required by release pipeline.
n/a
=> NETOBSERV-1633: Enable prefetch dependencies in konlfux build pipelines

controllers/flp/flp_controller.go, pkg/loki/roles.go, pkg/resources/static_resources.go
Prevent undesired mutation of the role by copying it before use.
n/a
=> NETOBSERV-1893: fix netobserv-mertics-reader role creation

controllers/flp/flp_controller.go, pkg/loki/roles.go, pkg/resources/static_resources.go
Prevent undesired mutation of the role by copying it before use.
backport of https://github.com/netobserv/network-observability-operator/pull/799
n/a
=> NETOBSERV-1893: fix netobserv-mertics-reader role creation [1.7 backport]

controllers/monitoring/monitoring_controller.go
Backport of https://github.com/netobserv/network-observability-operator/pull/806
=> NETOBSERV-1811 followup backport

controllers/constants/constants.go, controllers/networkpolicy/np_objects.go, main.go
It's actually using host/mp0 interface, so needs a "policy-group.network.openshift.io/host-network" label rule
n/a
=> NETOBSERV-1934: allow connection from apiserver

apis/flowcollector/v1beta2/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, docs/FlowCollector.md
Default namespaces are handled in code, do not add extra namespaces by default or they will be listed twice in the network policy
n/a
=> NETOBSERV-1933: do not set default additional namespaces for netpol

controllers/consoleplugin/config/static-frontend-config.yaml
Improve misleading descriptions
n/a
=> NETOBSERV-1885: improve resource filter descriptions

controllers/consoleplugin/config/static-frontend-config.yaml
depends on https://github.com/netobserv/network-observability-console-plugin/pull/633
=> Adapt columns in frontend config with changes in plugin

catalog.Dockerfile.downstream
Make base image for FBC configurable
n/a
=> Make base image for FBC configurable

controllers/consoleplugin/config/static-frontend-config.yaml, controllers/flp/flp_pipeline_builder.go, go.mod, go.sum, pkg/helper/cardinality/cardinality.json, vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/transform_network.go, vendor/github.com/netobserv/flowlogs-pipeline/pkg/utils/tcp_flags.go, vendor/modules.txt
Set tcp flags as a string field
Also change its cardinality to "careful", as it's any combination of values, it can be high potentially
- FLP: https://github.com/netobserv/flowlogs-pipeline/pull/747
- Console plugin: https://github.com/netobserv/network-observability-console-plugin/pull/632
=> NETOBSERV-1890: expand TCP flags as string in FLP

bundle/manifests/netobserv-operator.clusterserviceversion.yaml, hack/crd2csvSpecDesc.sh
We need to check if it fixes csv gen on mac.
Initial issue was mentioned here: https://github.com/netobserv/network-observability-operator/pull/912#discussion_r1868183836
=> OLM forms, fix display name generation for mac

config/samples/flowmetrics/flows_with_flags_per_destination.yaml, config/samples/flowmetrics/flows_with_flags_per_source.yaml
Update flowmetric samples that uses flags as https://github.com/netobserv/flowlogs-pipeline/pull/747 changed the decoding of tcp flags
n/a
=> update for new flags structure

controllers/consoleplugin/config/static-frontend-config.yaml
Simple config update to make CLI compatible
- added missing fields references when multiple fields were involved (console plugin takes the array in priority)
- added missing drop related fields (these will not be shown by default but selectable in the plugin)
n/a
=> NETOBSERV-1580: update frontend config for CLI

controllers/ebpf/agent_controller.go
there seems to be an issue with setting pkt translation flag when handling conflicts with other changes
n/a
=> Pkt translation envvar not been set correctly

.tekton/pipeline-fbc-ref.yaml
Updating konflux task due to breaking change and deprecated tasks
- removing fbc-related-image-check
- renaming task-fbc-validation
- removing inspect-image
See https://github.com/netobserv/network-observability-operator/pull/787
n/a
=> Updating konflux task due to breaking change and deprecated tasks

apis/flowcollector/v1beta2/flowcollector_validation_webhook.go, apis/flowcollector/v1beta2/flowcollector_validation_webhook_test.go
prevent users from using duplicate CIDR when configure multi filter rules
n/a
=> NETOBSERV-2048: Add webhook check to prevent CIDR duplication when configure multi rules filtering

controllers/consoleplugin/config/static-frontend-config.yaml
make sure zoneid column only shows when pktxlat feature is on
also include src and dst object as default column when feature is enabled
n/a
=> make sure zone_id is visible when pkt xlation feature is enabled

controllers/consoleplugin/config/static-frontend-config.yaml, controllers/flp/flp_test.go, pkg/helper/loki/labels_test.go, pkg/helper/loki/loki-labels.json
Update the config for UDNs to: 
- manage columns
-  filters
-  fields
-  scopes and groups 
https://github.com/netobserv/network-observability-console-plugin/pull/656 for some display polishing
=> NETOBSERV-1904 add configs for UDNs

apis/flowcollector/v1beta2/flowcollector_validation_webhook.go, apis/flowcollector/v1beta2/flowcollector_validation_webhook_test.go
update validationn check for 4.18 features NetworkEvent, UDNMapping and EbpfManager
and add OCP version check for pktDrop feature
n/a
=> update webhook check for 4.18 features and pktDrop

controllers/flp/flp_pipeline_builder.go
Automatically configure enrichment with secondary network config when UDN is configured
=> Automatic UDN enrichment

pkg/dashboards/health.go
https://github.com/netobserv/netobserv-ebpf-agent/pull/509
=> NETOBSERV-2075: [minor] Add agent severity to error metric

controllers/ebpf/agent_controller.go
add missing peer filter map to ebpf volume
```
oc get pods -n netobserv-privileged
NAME                         READY   STATUS             RESTARTS      AGE
netobserv-ebpf-agent-dcxwf   0/1     CrashLoopBackOff   1 (8s ago)    44s
netobserv-ebpf-agent-dssls   0/1     CrashLoopBackOff   1 (11s ago)   44s
netobserv-ebpf-agent-jpx58   0/1     CrashLoopBackOff   1 (13s ago)   44s
netobserv-ebpf-agent-pjslk   0/1     CrashLoopBackOff   1 (6s ago)    44s
netobserv-ebpf-agent-q7fzz   0/1     Error              2 (22s ago)   44s
netobserv-ebpf-agent-z7w6m   0/1     Error              2 (28s ago)   44s
oc logs -n netobserv-privileged netobserv-ebpf-agent-dcxwf
time="2025-01-28T15:02:39Z" level=info msg="starting NetObserv eBPF Agent [build version: main-528ec8c, build date: 2025-01-28 12:06]" …
```
=> Add missing peer map to bpfman volume

hack/container_digest.sh
Fixe typo in bundle images digests
n/a
=> Fixe typo in bundle images digests

apis/flowcollector/v1beta1/flowcollector_types.go, apis/flowcollector/v1beta1/zz_generated.conversion.go, apis/flowcollector/v1beta1/zz_generated.deepcopy.go, apis/flowcollector/v1beta2/flowcollector_types.go, apis/flowcollector/v1beta2/flowcollector_validation_webhook.go, apis/flowcollector/v1beta2/flowcollector_validation_webhook_test.go, apis/flowcollector/v1beta2/zz_generated.deepcopy.go, apis/flowmetrics/v1alpha1/flowmetric_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, bundle/manifests/flows.netobserv.io_flowmetrics.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/crd/bases/flows.netobserv.io_flowmetrics.yaml, controllers/consoleplugin/config/static-frontend-config.yaml, controllers/ebpf/agent_controller.go, docs/FlowCollector.md, docs/FlowMetric.md, docs/flowcollector-flows-netobserv-io-v1beta2.adoc, docs/flowmetric-flows-netobserv-io-v1alpha1.adoc, docs/flows-format.adoc, hack/asciidoc-flows-gen.sh, pkg/helper/cardinality/cardinality.json
=> Regenerate doc

Makefile, RELEASE.md, apis/flowcollector/v1beta1/flowcollector_types.go, apis/flowcollector/v1beta1/zz_generated.conversion.go, apis/flowcollector/v1beta1/zz_generated.deepcopy.go, apis/flowcollector/v1beta2/flowcollector_types.go, apis/flowcollector/v1beta2/flowcollector_validation_webhook.go, apis/flowcollector/v1beta2/flowcollector_validation_webhook_test.go, apis/flowcollector/v1beta2/zz_generated.deepcopy.go, apis/flowmetrics/v1alpha1/flowmetric_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, bundle/manifests/flows.netobserv.io_flowmetrics.yaml, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/crd/bases/flows.netobserv.io_flowmetrics.yaml, config/csv/bases/netobserv-operator.clusterserviceversion.yaml, config/descriptions/ocp.md, config/descriptions/upstream.md, config/manager/kustomization.yaml, config/manager/manager.yaml, controllers/consoleplugin/config/static-frontend-config.yaml, controllers/ebpf/agent_controller.go, docs/FlowCollector.md, docs/FlowMetric.md, docs/flowcollector-flows-netobserv-io-v1beta2.adoc, docs/flowmetric-flows-netobserv-io-v1alpha1.adoc, docs/flows-format.adoc, hack/asciidoc-flows-gen.sh, pkg/helper/cardinality/cardinality.json
Backport of https://github.com/netobserv/network-observability-operator/pull/1071
=> Regenerate doc [1.8 backport]

.tekton/pipeline-bundle-ref.yaml
This task is automatically skipped, but the skip now trigger a security violation in release pipeline.
n/a
=> Removing preflight check for bundle which  is skipped for bundle

.tekton/pipeline-bundle-ref.yaml
This task is automatically skipped, but the skip now trigger a security violation in release pipeline.
n/a
=> (backport) Removing preflight check which is skipped for bundles

.tekton/pipeline-fbc-ref.yaml
A new task in the FBC builder pipeline will soon become required by Konflux's Conforma policies.
The task definition can be found here:
- https://github.com/konflux-ci/build-definitions/tree/main/task/fbc-target-index-pruning-check/0.1
Ref:
- https://issues.redhat.com/browse/KONFLUX-3935
- https://issues.redhat.com/browse/CVP-4387
=> RELEASE BLOCKER(March 17, 2025): Add fbc-target-index-pruning-check to FBC pipelines

apis/flowcollector/v1beta2/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, docs/FlowCollector.md, helm/templates/flows.netobserv.io_flowcollectors.yaml, pkg/metrics/predefined_metrics.go
This is fixing wrong metrics that are due to accumulating bytes/packets counters from heartbits, which are not relevant for accumulation.
However, conversation tracking is still bad at providing accurate metrics for long-standing connections, as the ConnectionEnded event may be very long to come. So this is going to remain as a known limitation of Conversation Tracking.
I don't think there's any urgency to backport this on 1.8
n/a
=> NETOBSERV-1955: fix wrong metrics for conversation tracking

bundle/manifests/netobserv-config-watcher_rbac.authorization.k8s.io_v1_clusterrole.yaml, config/rbac/component_roles.yaml, controllers/flp/flp_monolith_reconciler.go, controllers/flp/flp_transfo_reconciler.go, pkg/resources/roles.go
=> Fix: config-watcher must be a ClusterRole

README.md
I'll open similar PRs on other repos when this one is validated
=> README: discussions and contributions

controllers/constants/constants.go, controllers/flp/flp_controller_test.go
See new role name here: https://github.com/netobserv/network-observability-operator/pull/1209/files#diff-e5a2e6e8caf9f06bb8c993c1db5500f89267fd7aeda28b9ac7e9461337b615c1
n/a
=> NETOBSERV-2185: fix loki writer role name

hack/nudging/container_digest.sh
=> Updating containers digests references

hack/nudging/container_digest.sh
Image created from 'https://github.com/netobserv/netobserv-ebpf-agent?rev=45cf6cfce75fcf2ede29876df32f349d1fcbfed8'
n/a
=> chore(deps): update netobserv-ebpf-agent-1-8 to 9a5e0f0

apis/flowcollector/v1beta2/flowcollector_validation_webhook_test.go, pkg/cluster/cluster.go
Openshift nightly builds don't follow semver conventions: they're like `4.18.0-0.nightly-2025-03-20-063534` even if they're after 4.18.6. In semver, that's considered as a 4.18.0 pre-release, so it is technically _less than_ 4.18.0.
I'm relaxing here the checks for version to just ignore the pre-release information, so `4.18.0-0.nightly-2025-03-20-063534` == `4.18.0`
n/a
=> NETOBSERV-2190: fix openshift version check with nightly builds

apis/flowcollector/v1beta2/flowcollector_validation_webhook.go, apis/flowcollector/v1beta2/flowcollector_validation_webhook_test.go
make sure OCP4.19 is required for network events, UDN and eventMgr
n/a
=> NETOBSERV-2194:: use OCP4.19 version check for networkEvents/UDN/ebpfMgr

apis/flowcollector/v1beta1/flowcollector_types.go, apis/flowcollector/v1beta2/flowcollector_types.go, apis/flowcollector/v1beta2/flowcollector_validation_webhook.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, config/samples/flows_v1beta2_flowcollector.yaml, controllers/consoleplugin/config/static-frontend-config.yaml, controllers/consoleplugin/consoleplugin_objects.go, controllers/ebpf/agent_controller.go, controllers/ebpf/bpfmanager-controller.go, docs/FlowCollector.md, helm/templates/flows.netobserv.io_flowcollectors.yaml, pkg/helper/flowcollector.go
https://github.com/netobserv/netobserv-ebpf-agent/pull/538
=> NETOBSERV-2198: IPsec support

bundle/manifests/netobserv-operator.clusterserviceversion.yaml, catalog/released/bundles.yaml, catalog/unreleased/downstream-test-fbc/bundle.yaml, config/descriptions/ocp.md, config/descriptions/upstream.md
Table taken from https://github.com/skrthomas/openshift-docs/blob/main/modules/network-observability-resources-table.adoc?plain=1 and converted to markdown.
n/a
=> NETOBSERV-1929 add resources recommendations to install page

bundle/manifests/netobserv-operator.clusterserviceversion.yaml, catalog/released/bundles.yaml, config/csv/bases/netobserv-operator.clusterserviceversion.yaml
Add Network Observability to the "Observability" category.  The "Observability" category has been added to the set of defaults in [https://github.com/operator-framework/api/blob/master/pkg/validation/internal/standardcategories.go#L31](https://github.com/operator-framework/api/blob/master/pkg/validation/internal/standardcategories.go#L31)
For bundles.yaml, it is only done for 1.8.0.
Fixes [OCPSTRAT-954](https://issues.redhat.com/browse/OCPSTRAT-954) and [NETOBSERV-1340](https://issues.redhat.com/browse/NETOBSERV-1340)
=> Add operator to "Observability" category in OperatorHub

bundle/manifests/netobserv-informers_rbac.authorization.k8s.io_v1_clusterrole.yaml, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/rbac/component_roles.yaml, config/rbac/role.yaml, controllers/consoleplugin/config/config.go, controllers/consoleplugin/config/static-frontend-config.yaml, controllers/consoleplugin/consoleplugin_objects.go, helm/templates/clusterrole.yaml, pkg/helper/flowcollector.go, pkg/manager/manager.go
- multiNetworks feature is enabled if UDN or secondary indexes are enabled
- By default, don't show UDN labels, but show NetworkName columns instead
Console plugin: https://github.com/netobserv/network-observability-console-plugin/pull/846
=> NETOBSERV-2227: plugin feature "multiNetworks", and promote NetworkName columns

controllers/consoleplugin/config/static-frontend-config.yaml
agent: https://github.com/netobserv/netobserv-ebpf-agent/pull/708
flp: https://github.com/netobserv/flowlogs-pipeline/pull/976
=> NETOBSERV-2222: single column ipsec status

internal/controller/ebpf/agent_controller.go, internal/controller/ebpf/agent_controller_test.go, internal/pkg/helper/env.go, internal/pkg/helper/env_test.go
Add the default tcx attach mode, except when openshift <= 4.14 is detected, then use tc hook
There's a small refactoring added to how EnvVar are created, because they were previously creating duplicates when overriding default values - which kinda still works, but isn't clean. This is now covered by tests.
n/a
=> NETOBSERV-2290: fix using tc hook for ocp4.14

api/flowcollector/v1beta2/flowcollector_types.go, bundle/manifests/flows.netobserv.io_flowcollectors.yaml, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/crd/bases/flows.netobserv.io_flowcollectors.yaml, docs/FlowCollector.md, docs/flowcollector-flows-netobserv-io-v1beta2.adoc, docs/flows-format.adoc, helm/templates/flows.netobserv.io_flowcollectors.yaml, internal/controller/consoleplugin/config/static-frontend-config.yaml
Tracking feedback from https://github.com/openshift/openshift-docs/pull/94756
=> Reinject doc feedback

api/flowmetrics/v1alpha1/flowmetric_types.go, bundle/manifests/flows.netobserv.io_flowmetrics.yaml, config/crd/bases/flows.netobserv.io_flowmetrics.yaml, docs/FlowMetric.md, helm/crds/flows.netobserv.io_flowmetrics.yaml, internal/controller/flp/flp_pipeline_builder.go, internal/controller/flp/flp_pipeline_builder_test.go, internal/controller/flp/flp_test.go, internal/controller/flp/fmstatus/flowmetrics_status.go, internal/pkg/helper/helpers.go, internal/pkg/helper/helpers_test.go
Also, improve printColumn to show the final metric name in prometheus
Add a test
n/a
=> NETOBSERV-2286: automatic metric naming after resource name

internal/controller/constants/constants.go, internal/controller/ebpf/agent_controller.go, internal/controller/ebpf/agent_metrics.go, internal/controller/flp/flp_monolith_objects.go, internal/controller/flp/flp_monolith_reconciler.go, internal/controller/flp/flp_transfo_objects.go, internal/controller/flp/flp_transfo_reconciler.go, internal/pkg/dashboards/health.go
Use scrape_samples_post_metric_relabeling instead of "count({__name__=~"netobserv_.*"})", which can be orders of magnitude faster on large clusters. It gives approximately the same values (the cardinality is a bit higher, because of generic metrics provided by our jobs but not directly from us, e.g. Go metrics)
Also move & export some constants to constants.go
See also: https://github.com/openshift-eng/ocp-qe-perfscale-ci/pull/799
**Before:**
**After:**
n/a
=> [Trivial] Use faster way to get metrics cardinality

internal/controller/monitoring/monitoring_controller.go, internal/pkg/helper/flowcollector.go
Fix namespace reconciliation when create by the user.
Since https://github.com/netobserv/network-observability-operator/pull/1345 `openshift.io/cluster-monitoring: "true"` is missing when the user created the namespace by himself.
n/a
=> NETOBSERV-2225 - Deploy static plugin at operator startup - fix

internal/controller/constants/constants.go, internal/controller/networkpolicy/np_objects.go, internal/controller/networkpolicy/np_test.go
Adding egress support to network policy
n/a
=> NETOBSERV-2294: Adding egress support to network policy

config/descriptions/ocp.md
Fix the link to "Installing the Network Observability Operator"
n/a
=> Fix doc link to net obs operator installation

Makefile
Deploy CSV when using make deploy to get the static forms schema.
Operator hub will show an error in the operator listed but witout impact on the usage.
n/a
=> deploy csv from makefile

Makefile, bundle/manifests/netobserv-operator.clusterserviceversion.yaml, config/manager/manager.yaml
The Makefile was screwing up the bundle when running first `make deploy` then `make update-bundle` (we had to manually discard changes from `make deploy` before running  `make update-bundle`  to avoid that)
This change updates all `sed` commands when updating manager.yaml so that it substitute next lines based on RELATED_IMAGE_X.
Note that we actually don't provide a plugin compat image in the community releases, so the tag `v1.9.2-community-pf4` is essentially a placeholder here. But we do support creating upstream OLM bundle/catalog for testing purpose, and this must work as well with compat images.
=> Fix upstream deploy/bundle issues with PF4 image

api/flowcollector/v1beta2/flowcollector_validation_webhook.go, api/flowcollector/v1beta2/flowcollector_validation_webhook_test.go, internal/controller/consoleplugin/consoleplugin_test.go, internal/controller/ebpf/agent_controller.go, internal/controller/flp/flp_common_objects.go, internal/controller/flp/flp_pipeline_builder.go, internal/controller/flp/flp_test.go, internal/pkg/helper/comparators.go, internal/pkg/helper/flowcollector.go
- Do not set default toleration on console plugin and FLP transfo (keep for FLP monolith as they must have a scheduling config consistent with agent pods)
- Allow override Tolerations and NodeSelectors with empty values
- Check for Toleration changes for reconcile triggers
- Add tests
- Add validation webhook to warn about inconsistent scheduling between Agent and FLP in direct mode
n/a
=> NETOBSERV-2434: fix default tolerations, and a few other issues
